services:

  app:
    build: ./app
    container_name: front-end 
    volumes: ['./app/src:/appcode']
    ports:
      - "8501:8501"

  api:
    build: ./api
    container_name: web-api
    depends_on:
      - db
    volumes: ['./api:/apicode']
    ports:
      - "4000:4000"
    environment:
      - DB_HOST=db
      - DB_PORT=3306

  db:
    image: mysql:8.0
    container_name: mysql_db
    env_file:
      - ./api/.env
    volumes:
      - ./database-files:/docker-entrypoint-initdb.d/:ro
    ports:
      - "3306:3306"
    