# ------------------------------------------------------------
# In this file, you can make some modifications to the Streamlit
# app's global environment. 
#
# All of the possible config options can be found here:
# https://docs.streamlit.io/develop/api-reference/configuration/config.toml
# ------------------------------------------------------------


[client]
# Turning the default sidebar navigation off so we 
# can use our own
showSidebarNavigation = false


# Setting some basic config options related to the theme of the app
[theme]
base="light"
primaryColor="#cc0000"
secondaryBackgroundColor="#f2f2f2"
textColor="#000000"

