-- CityCommunity Data

-- Housing Data
insert into Housing (HousingID, Availability, Style, Location) values (1, 'occupied', 'Yurt', 'North End');
insert into Housing (HousingID, Availability, Style, Location) values (2, 'occupied', 'Yurt', 'Midtown');
insert into Housing (HousingID, Availability, Style, Location) values (3, 'vacant', 'Mobile Home', 'North End');
insert into Housing (HousingID, Availability, Style, Location) values (4, 'under contract', 'Fraternity/Sorority House', 'South Side');
insert into Housing (HousingID, Availability, Style, Location) values (5, 'coming soon', 'Apartment', 'South Side');
insert into Housing (HousingID, Availability, Style, Location) values (6, 'pending inspection', 'Apartment', 'East Side');
insert into Housing (HousingID, Availability, Style, Location) values (7, 'occupied', 'Tiny House', 'West End');
insert into Housing (HousingID, Availability, Style, Location) values (8, 'under contract', 'Loft', 'Downtown');
insert into Housing (HousingID, Availability, Style, Location) values (9, 'for sale', 'Mobile Home', 'South Side');
insert into Housing (HousingID, Availability, Style, Location) values (10, 'leased', 'Mobile Home', 'South Side');
insert into Housing (HousingID, Availability, Style, Location) values (11, 'pending inspection', 'Townhouse', 'East Side');
insert into Housing (HousingID, Availability, Style, Location) values (12, 'vacant', 'Treehouse', 'North End');
insert into Housing (HousingID, Availability, Style, Location) values (13, 'vacant', 'Fraternity/Sorority House', 'South Side');
insert into Housing (HousingID, Availability, Style, Location) values (14, 'under contract', 'Townhouse', 'West End');
insert into Housing (HousingID, Availability, Style, Location) values (15, 'off market', 'Fraternity/Sorority House', 'East Side');
insert into Housing (HousingID, Availability, Style, Location) values (16, 'under contract', 'Loft', 'Downtown');
insert into Housing (HousingID, Availability, Style, Location) values (17, 'off market', 'Tiny House', 'Midtown');
insert into Housing (HousingID, Availability, Style, Location) values (18, 'occupied', 'Apartment', 'East Side');
insert into Housing (HousingID, Availability, Style, Location) values (19, 'coming soon', 'Cottage', 'North End');
insert into Housing (HousingID, Availability, Style, Location) values (20, 'for sale', 'Treehouse', 'West End');
insert into Housing (HousingID, Availability, Style, Location) values (21, 'leased', 'Treehouse', 'East Side');
insert into Housing (HousingID, Availability, Style, Location) values (22, 'for sale', 'Yurt', 'North End');
insert into Housing (HousingID, Availability, Style, Location) values (23, 'for sale', 'Yurt', 'North End');
insert into Housing (HousingID, Availability, Style, Location) values (24, 'occupied', 'Apartment', 'West End');
insert into Housing (HousingID, Availability, Style, Location) values (25, 'occupied', 'Cottage', 'Downtown');
insert into Housing (HousingID, Availability, Style, Location) values (26, 'off market', 'Apartment', 'East Side');
insert into Housing (HousingID, Availability, Style, Location) values (27, 'vacant', 'Loft', 'North End');
insert into Housing (HousingID, Availability, Style, Location) values (28, 'under contract', 'Tiny House', 'Midtown');
insert into Housing (HousingID, Availability, Style, Location) values (29, 'leased', 'Yurt', 'North End');
insert into Housing (HousingID, Availability, Style, Location) values (30, 'for sale', 'Dormitory', 'West End');
insert into Housing (HousingID, Availability, Style, Location) values (31, 'occupied', 'Mobile Home', 'South Side');
insert into Housing (HousingID, Availability, Style, Location) values (32, 'leased', 'Dormitory', 'North End');
insert into Housing (HousingID, Availability, Style, Location) values (33, 'occupied', 'Cottage', 'North End');
insert into Housing (HousingID, Availability, Style, Location) values (34, 'off market', 'Yurt', 'West End');
insert into Housing (HousingID, Availability, Style, Location) values (35, 'occupied', 'Loft', 'Uptown');
insert into Housing (HousingID, Availability, Style, Location) values (36, 'pending inspection', 'Tiny House', 'South Side');
insert into Housing (HousingID, Availability, Style, Location) values (37, 'occupied', 'Fraternity/Sorority House', 'Uptown');
insert into Housing (HousingID, Availability, Style, Location) values (38, 'under contract', 'Yurt', 'East Side');
insert into Housing (HousingID, Availability, Style, Location) values (39, 'leased', 'Dormitory', 'East Side');
insert into Housing (HousingID, Availability, Style, Location) values (40, 'coming soon', 'Tiny House', 'West End');
insert into Housing (HousingID, Availability, Style, Location) values (41, 'available', 'Tiny House', 'South Side');
insert into Housing (HousingID, Availability, Style, Location) values (42, 'available', 'Loft', 'South Side');
insert into Housing (HousingID, Availability, Style, Location) values (43, 'available', 'Tiny House', 'West End');
insert into Housing (HousingID, Availability, Style, Location) values (44, 'pending inspection', 'Yurt', 'East Side');
insert into Housing (HousingID, Availability, Style, Location) values (45, 'available', 'Townhouse', 'West End');
insert into Housing (HousingID, Availability, Style, Location) values (46, 'occupied', 'Cottage', 'North End');
insert into Housing (HousingID, Availability, Style, Location) values (47, 'vacant', 'Townhouse', 'South Side');
insert into Housing (HousingID, Availability, Style, Location) values (48, 'coming soon', 'Townhouse', 'Midtown');
insert into Housing (HousingID, Availability, Style, Location) values (49, 'under renovation', 'Cottage', 'Downtown');
insert into Housing (HousingID, Availability, Style, Location) values (50, 'leased', 'Yurt', 'East Side');
