USE cosint;

-- mock data for applications
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for backend engineer', 2.7, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for Software Engineer Intern', 2.9, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for backend engineer', 3.5, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for Software Engineer Intern', 2.6, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for Full-Stack Engineer', 3.9, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for Software Engineer Intern', 3.1, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for Full-Stack Engineer', 3.9, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for Full-Stack Engineer', 3.5, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for database management', 2.9, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for Full-Stack Engineer', 3.9, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for backend engineer', 2.9, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for database management', 3.3, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for Software Engineer Intern', 2.9, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for Software Engineer Intern', 3.8, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for Full-Stack Engineer', 3.3, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for backend engineer', 3.7, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for backend engineer', 3.0, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for Full-Stack Engineer', 3.7, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for backend engineer', 4.0, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for Software Engineer Intern', 3.7, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for database management', 2.6, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for backend engineer', 3.7, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for Full-Stack Engineer', 3.0, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for Software Engineer Intern', 3.1, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for Software Engineer Intern', 3.8, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for Software Engineer Intern', 2.9, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for database management', 3.0, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for Software Engineer Intern', 3.2, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for backend engineer', 3.1, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for Full-Stack Engineer', 3.5, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for Full-Stack Engineer', 3.1, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for database management', 3.8, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for database management', 3.7, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for backend engineer', 2.8, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for Software Engineer Intern', 3.2, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for database management', 3.9, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for Software Engineer Intern', 2.7, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for Full-Stack Engineer', 3.0, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for backend engineer', 3.9, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for Full-Stack Engineer', 4.0, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for Software Engineer Intern', 2.7, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for database management', 4.0, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for backend engineer', 2.6, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for database management', 3.7, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for backend engineer', 2.9, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for database management', 3.8, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for database management', 2.9, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for database management', 2.7, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for database management', 3.7, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for Software Engineer Intern', 3.6, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for backend engineer', 2.8, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for Full-Stack Engineer', 3.8, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for Full-Stack Engineer', 3.1, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for database management', 3.4, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for Software Engineer Intern', 3.0, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for database management', 3.2, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for database management', 3.0, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for database management', 3.1, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for database management', 3.6, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for database management', 2.6, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for database management', 3.1, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for Software Engineer Intern', 2.8, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for database management', 3.6, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for Software Engineer Intern', 3.3, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for database management', 3.7, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for Software Engineer Intern', 3.9, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for Full-Stack Engineer', 2.5, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for Full-Stack Engineer', 2.8, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for Software Engineer Intern', 3.8, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for Software Engineer Intern', 3.9, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for database management', 2.9, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for Full-Stack Engineer', 2.5, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for database management', 3.2, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for backend engineer', 3.5, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for backend engineer', 3.5, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for database management', 3.6, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for Software Engineer Intern', 3.2, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for Full-Stack Engineer', 3.6, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for Software Engineer Intern', 2.7, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for Full-Stack Engineer', 3.7, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for Full-Stack Engineer', 3.6, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for Full-Stack Engineer', 3.7, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for database management', 2.8, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for Full-Stack Engineer', 3.8, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for Software Engineer Intern', 2.8, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for Software Engineer Intern', 2.6, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for Full-Stack Engineer', 2.9, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for Full-Stack Engineer', 3.9, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for Full-Stack Engineer', 3.1, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for Software Engineer Intern', 3.5, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for database management', 2.9, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for database management', 3.5, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for Software Engineer Intern', 3.1, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for backend engineer', 3.4, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for Full-Stack Engineer', 3.7, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for Full-Stack Engineer', 3.7, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for Full-Stack Engineer', 3.3, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for Full-Stack Engineer', 3.8, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for Software Engineer Intern', 2.6, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for backend engineer', 3.3, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for Software Engineer Intern', 3.7, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for Full-Stack Engineer', 3.5, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for Full-Stack Engineer', 2.9, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for Software Engineer Intern', 3.1, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for backend engineer', 3.3, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for backend engineer', 3.5, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for Software Engineer Intern', 3.9, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for Software Engineer Intern', 2.7, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for Software Engineer Intern', 2.7, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for Software Engineer Intern', 3.9, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for backend engineer', 3.7, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for backend engineer', 3.8, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for backend engineer', 3.3, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for Software Engineer Intern', 3.2, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for Full-Stack Engineer', 2.6, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for database management', 2.8, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for backend engineer', 3.1, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for Full-Stack Engineer', 2.8, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for Full-Stack Engineer', 3.4, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for backend engineer', 3.1, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for backend engineer', 3.5, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for backend engineer', 3.9, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for Software Engineer Intern', 3.8, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for Full-Stack Engineer', 3.1, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for Software Engineer Intern', 3.1, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for Full-Stack Engineer', 3.8, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for database management', 2.7, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for Full-Stack Engineer', 2.9, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for database management', 3.6, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for backend engineer', 3.7, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for Full-Stack Engineer', 3.3, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for Full-Stack Engineer', 2.9, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for backend engineer', 3.4, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for Full-Stack Engineer', 3.3, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for backend engineer', 2.5, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for Software Engineer Intern', 2.9, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for Software Engineer Intern', 2.6, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for database management', 3.8, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for database management', 3.1, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for Software Engineer Intern', 3.9, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for Software Engineer Intern', 2.6, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for database management', 2.5, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for Software Engineer Intern', 3.9, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for Software Engineer Intern', 2.7, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for Full-Stack Engineer', 3.0, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for Software Engineer Intern', 3.2, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for backend engineer', 3.5, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for backend engineer', 2.5, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for backend engineer', 3.1, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for database management', 3.4, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for Software Engineer Intern', 2.5, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for backend engineer', 3.8, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for Full-Stack Engineer', 3.3, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for Software Engineer Intern', 4.0, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for database management', 3.3, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for database management', 2.5, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for backend engineer', 2.7, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for Full-Stack Engineer', 2.8, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for backend engineer', 3.2, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for backend engineer', 3.2, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for backend engineer', 3.8, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for Full-Stack Engineer', 3.1, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for Full-Stack Engineer', 3.9, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for Full-Stack Engineer', 3.4, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for backend engineer', 3.9, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for Full-Stack Engineer', 3.4, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for database management', 2.6, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for Full-Stack Engineer', 2.9, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for Software Engineer Intern', 3.6, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for Software Engineer Intern', 2.8, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for Software Engineer Intern', 2.6, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for backend engineer', 2.8, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for Full-Stack Engineer', 3.3, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for Software Engineer Intern', 3.5, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for Software Engineer Intern', 3.5, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for database management', 2.9, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for database management', 3.0, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for backend engineer', 2.6, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for Full-Stack Engineer', 3.6, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for Software Engineer Intern', 3.1, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for backend engineer', 3.2, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for database management', 2.6, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for database management', 3.8, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for Software Engineer Intern', 3.6, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for Full-Stack Engineer', 3.8, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for database management', 3.1, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for database management', 3.0, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for Software Engineer Intern', 3.1, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for database management', 3.9, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for backend engineer', 2.7, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for Software Engineer Intern', 3.4, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for backend engineer', 3.0, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for backend engineer', 2.7, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for backend engineer', 4.0, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for Full-Stack Engineer', 2.9, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for Full-Stack Engineer', 2.6, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for backend engineer', 3.1, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for database management', 3.4, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for database management', 3.7, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for Full-Stack Engineer', 3.5, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for backend engineer', 3.4, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for Full-Stack Engineer', 3.3, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for Full-Stack Engineer', 2.8, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for Full-Stack Engineer', 3.6, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for database management', 3.8, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for Software Engineer Intern', 3.5, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for Software Engineer Intern', 3.1, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for Software Engineer Intern', 3.5, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for Software Engineer Intern', 3.2, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for Software Engineer Intern', 3.9, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for Full-Stack Engineer', 3.1, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for backend engineer', 3.0, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for database management', 2.9, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for database management', 3.7, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for backend engineer', 2.6, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for Full-Stack Engineer', 3.7, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for backend engineer', 3.4, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for Software Engineer Intern', 2.7, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for Full-Stack Engineer', 3.9, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for Full-Stack Engineer', 2.6, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for backend engineer', 3.6, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for backend engineer', 3.5, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for database management', 3.9, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for Software Engineer Intern', 3.6, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for backend engineer', 3.3, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for database management', 2.8, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for backend engineer', 2.6, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for database management', 2.8, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for Full-Stack Engineer', 2.6, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for backend engineer', 2.9, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for backend engineer', 3.0, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for backend engineer', 3.5, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for backend engineer', 2.9, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for Full-Stack Engineer', 3.5, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for database management', 3.6, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for backend engineer', 3.9, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for backend engineer', 3.1, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for database management', 3.3, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for Full-Stack Engineer', 3.2, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for backend engineer', 2.8, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for Full-Stack Engineer', 2.7, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for database management', 2.8, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for backend engineer', 2.5, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for database management', 3.6, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for database management', 2.9, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for backend engineer', 3.9, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for Full-Stack Engineer', 3.4, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for Software Engineer Intern', 3.7, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for Full-Stack Engineer', 3.4, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for Software Engineer Intern', 3.7, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for database management', 3.6, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for backend engineer', 3.9, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for Full-Stack Engineer', 3.8, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for Software Engineer Intern', 3.7, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for backend engineer', 3.4, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for database management', 3.9, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for Full-Stack Engineer', 2.9, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for backend engineer', 3.6, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for Software Engineer Intern', 3.5, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for Full-Stack Engineer', 3.6, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for Software Engineer Intern', 3.6, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for database management', 3.6, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for Software Engineer Intern', 3.6, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for Software Engineer Intern', 2.8, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for backend engineer', 2.8, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for backend engineer', 3.7, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for database management', 2.5, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for database management', 2.6, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for Software Engineer Intern', 3.0, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for Software Engineer Intern', 2.7, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for Software Engineer Intern', 3.5, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for Full-Stack Engineer', 2.5, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for backend engineer', 2.9, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for database management', 3.6, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for database management', 2.6, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for Software Engineer Intern', 3.9, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for Software Engineer Intern', 3.3, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for Software Engineer Intern', 3.0, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for Software Engineer Intern', 2.8, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for backend engineer', 3.3, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for database management', 3.6, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for Software Engineer Intern', 3.4, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for Software Engineer Intern', 3.1, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for backend engineer', 3.9, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for Software Engineer Intern', 3.8, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for database management', 3.2, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for Full-Stack Engineer', 3.0, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for Full-Stack Engineer', 2.8, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for backend engineer', 3.8, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for Full-Stack Engineer', 3.2, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for Software Engineer Intern', 3.3, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for Software Engineer Intern', 3.8, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for backend engineer', 3.7, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for Software Engineer Intern', 3.5, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for Software Engineer Intern', 3.2, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for Full-Stack Engineer', 3.6, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for backend engineer', 3.1, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for Software Engineer Intern', 2.9, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for Software Engineer Intern', 3.7, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for database management', 2.6, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for database management', 3.1, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for Full-Stack Engineer', 3.1, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for Full-Stack Engineer', 3.1, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for Full-Stack Engineer', 2.7, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for Full-Stack Engineer', 3.6, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for database management', 3.8, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for backend engineer', 2.7, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for backend engineer', 3.6, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for Full-Stack Engineer', 2.8, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for Full-Stack Engineer', 3.6, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for database management', 3.0, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for Software Engineer Intern', 2.7, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for Full-Stack Engineer', 3.6, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for database management', 2.7, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for Software Engineer Intern', 3.1, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for Full-Stack Engineer', 4.0, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for backend engineer', 2.5, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for Software Engineer Intern', 3.2, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for database management', 2.8, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for database management', 2.6, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for Full-Stack Engineer', 3.3, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for database management', 3.5, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for Full-Stack Engineer', 3.5, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for Full-Stack Engineer', 3.6, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for Full-Stack Engineer', 3.2, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for Software Engineer Intern', 3.5, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for Full-Stack Engineer', 2.8, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for Software Engineer Intern', 3.2, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for Full-Stack Engineer', 2.6, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for backend engineer', 3.3, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for Full-Stack Engineer', 3.3, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for Full-Stack Engineer', 3.5, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for Full-Stack Engineer', 3.9, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for Software Engineer Intern', 3.3, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for backend engineer', 3.7, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for backend engineer', 2.5, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for Full-Stack Engineer', 3.5, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for Full-Stack Engineer', 4.0, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for backend engineer', 3.0, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for backend engineer', 2.8, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for database management', 2.6, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for database management', 3.4, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for Full-Stack Engineer', 3.7, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for database management', 2.7, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for Software Engineer Intern', 2.9, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for Software Engineer Intern', 3.2, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for backend engineer', 3.8, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for database management', 3.4, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for Software Engineer Intern', 3.3, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for backend engineer', 2.6, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for database management', 2.8, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for database management', 3.0, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for Full-Stack Engineer', 3.7, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for backend engineer', 2.9, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for backend engineer', 3.8, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for backend engineer', 3.1, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for backend engineer', 2.6, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for database management', 3.0, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for Software Engineer Intern', 3.7, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for backend engineer', 3.6, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for Full-Stack Engineer', 3.5, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for Full-Stack Engineer', 3.6, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for Full-Stack Engineer', 3.9, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for Full-Stack Engineer', 2.9, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for backend engineer', 4.0, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for backend engineer', 2.6, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for database management', 3.4, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for Software Engineer Intern', 3.9, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for Software Engineer Intern', 2.6, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for Software Engineer Intern', 3.8, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for backend engineer', 3.5, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for Software Engineer Intern', 3.7, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for Software Engineer Intern', 2.8, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for Full-Stack Engineer', 3.5, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for Software Engineer Intern', 3.3, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for database management', 3.5, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for database management', 3.4, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for Software Engineer Intern', 3.0, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for backend engineer', 2.7, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for backend engineer', 3.5, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for Software Engineer Intern', 2.9, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for Full-Stack Engineer', 2.8, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for Software Engineer Intern', 2.7, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for Full-Stack Engineer', 2.6, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for Full-Stack Engineer', 3.9, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for Full-Stack Engineer', 3.2, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for backend engineer', 2.6, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for database management', 3.1, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for Software Engineer Intern', 2.6, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for database management', 3.1, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for Full-Stack Engineer', 3.0, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for database management', 3.8, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for backend engineer', 2.9, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for database management', 2.7, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for Software Engineer Intern', 3.0, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for Full-Stack Engineer', 3.8, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for Software Engineer Intern', 3.9, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for database management', 2.7, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for backend engineer', 3.7, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for backend engineer', 3.1, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for Software Engineer Intern', 3.9, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for database management', 3.4, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for Software Engineer Intern', 2.9, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for backend engineer', 3.2, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for backend engineer', 3.4, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for backend engineer', 3.2, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for backend engineer', 2.7, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for backend engineer', 3.0, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for database management', 3.4, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for Full-Stack Engineer', 2.7, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for Software Engineer Intern', 2.6, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for Full-Stack Engineer', 3.9, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for Full-Stack Engineer', 2.9, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for database management', 2.7, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for Full-Stack Engineer', 3.9, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for Software Engineer Intern', 4.0, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for Software Engineer Intern', 3.1, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for database management', 3.2, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for Software Engineer Intern', 2.7, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for database management', 3.6, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for Full-Stack Engineer', 2.7, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for database management', 2.8, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for database management', 2.9, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for database management', 2.5, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for database management', 2.5, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for Full-Stack Engineer', 3.9, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for database management', 3.0, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for database management', 3.3, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for backend engineer', 3.0, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for Full-Stack Engineer', 2.6, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for backend engineer', 3.6, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for Full-Stack Engineer', 2.8, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for database management', 3.1, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for Full-Stack Engineer', 3.3, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for database management', 3.6, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for database management', 2.9, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for Software Engineer Intern', 3.7, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for backend engineer', 2.9, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for Software Engineer Intern', 2.6, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for database management', 2.6, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for database management', 3.6, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for database management', 3.8, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for Full-Stack Engineer', 2.7, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for backend engineer', 3.1, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for Full-Stack Engineer', 3.5, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for Software Engineer Intern', 3.6, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for database management', 3.8, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for database management', 3.2, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for database management', 2.7, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for database management', 4.0, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for Full-Stack Engineer', 2.9, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for Full-Stack Engineer', 3.0, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for backend engineer', 3.9, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for database management', 3.9, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for backend engineer', 3.0, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for Full-Stack Engineer', 3.9, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for Full-Stack Engineer', 2.9, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for Full-Stack Engineer', 2.5, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for backend engineer', 3.2, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for Software Engineer Intern', 4.0, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for backend engineer', 3.2, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for Software Engineer Intern', 4.0, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for database management', 3.6, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for Full-Stack Engineer', 2.7, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for backend engineer', 2.8, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for Software Engineer Intern', 3.2, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for Full-Stack Engineer', 2.6, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for Full-Stack Engineer', 3.1, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for backend engineer', 3.9, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for Full-Stack Engineer', 3.0, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for Full-Stack Engineer', 3.5, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for database management', 3.0, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for backend engineer', 3.0, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for Software Engineer Intern', 3.1, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for backend engineer', 3.7, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for Software Engineer Intern', 2.7, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for backend engineer', 3.7, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for backend engineer', 3.5, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for backend engineer', 3.3, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for Software Engineer Intern', 2.8, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for backend engineer', 3.8, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for backend engineer', 2.8, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for Full-Stack Engineer', 3.5, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for database management', 3.5, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for Full-Stack Engineer', 2.6, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for database management', 3.0, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for backend engineer', 3.6, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for backend engineer', 3.2, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for database management', 3.4, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for backend engineer', 3.5, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for Full-Stack Engineer', 3.4, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for Full-Stack Engineer', 2.7, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for backend engineer', 3.4, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I interned at Google last summer', 'Application for Full-Stack Engineer', 3.4, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for Full-Stack Engineer', 2.8, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for Software Engineer Intern', 3.5, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for backend engineer', 3.4, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 5 years of experience in Python', 'Application for Full-Stack Engineer', 3.1, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for backend engineer', 3.4, 'NOW()');
insert into applications (questionResponse, summary, GPA, submittedAt) values ('I have 2 years of experience in SQL', 'Application for database management', 2.9, 'NOW()');
