USE cosint;

-- mock data for notable skills
insert into notable_skills (applicationId, name, summary) values (397, 'Volunteer Training', 'Developed a new algorithm to predict bitcoin prices');
insert into notable_skills (applicationId, name, summary) values (162, 'jQuery UI', 'Developed a new algorithm to predict bitcoin prices');
insert into notable_skills (applicationId, name, summary) values (107, 'CMake', 'Managed a team of 20 software interns');
insert into notable_skills (applicationId, name, summary) values (401, 'Business Transformation', 'Created a web application that tracks the user''s daily caloric intake');
insert into notable_skills (applicationId, name, summary) values (145, 'Audio Editing', 'Managed a team of 20 software interns');
insert into notable_skills (applicationId, name, summary) values (430, 'Socket.io', 'Designed a new UI for Google');
insert into notable_skills (applicationId, name, summary) values (22, 'Xactly', 'Created a web application that tracks the user''s daily caloric intake');
insert into notable_skills (applicationId, name, summary) values (227, 'Abstracting', 'Managed a team of 20 software interns');
insert into notable_skills (applicationId, name, summary) values (123, 'TCM', 'Managed a team of 20 software interns');
insert into notable_skills (applicationId, name, summary) values (355, 'Employment Law', 'Managed a team of 20 software interns');
insert into notable_skills (applicationId, name, summary) values (233, 'Direct Marketing', 'Managed a team of 20 software interns');
insert into notable_skills (applicationId, name, summary) values (176, 'CP', 'Managed a team of 20 software interns');
insert into notable_skills (applicationId, name, summary) values (488, 'Icon Design', 'Managed a team of 20 software interns');
insert into notable_skills (applicationId, name, summary) values (499, 'HDI', 'Designed a new UI for Google');
insert into notable_skills (applicationId, name, summary) values (110, 'Non-Conforming', 'Managed a team of 20 software interns');
insert into notable_skills (applicationId, name, summary) values (348, 'Hudson', 'Created a web application that tracks the user''s daily caloric intake');
insert into notable_skills (applicationId, name, summary) values (488, 'MBCS', 'Developed a new algorithm to predict bitcoin prices');
insert into notable_skills (applicationId, name, summary) values (99, 'Bankruptcy', 'Managed a team of 20 software interns');
insert into notable_skills (applicationId, name, summary) values (149, 'JPAS', 'Designed a new UI for Google');
insert into notable_skills (applicationId, name, summary) values (431, 'CTC', 'Developed a new algorithm to predict bitcoin prices');
insert into notable_skills (applicationId, name, summary) values (310, 'Honeywell DCS', 'Designed a new UI for Google');
insert into notable_skills (applicationId, name, summary) values (141, 'DCF Valuation', 'Developed a new algorithm to predict bitcoin prices');
insert into notable_skills (applicationId, name, summary) values (466, 'UPS Systems', 'Managed a team of 20 software interns');
insert into notable_skills (applicationId, name, summary) values (154, 'FI-AA', 'Created a web application that tracks the user''s daily caloric intake');
insert into notable_skills (applicationId, name, summary) values (424, 'Applied Mathematics', 'Designed a new UI for Google');
insert into notable_skills (applicationId, name, summary) values (65, 'Hummingbird DM', 'Designed a new UI for Google');
insert into notable_skills (applicationId, name, summary) values (477, 'Business Owner Planning', 'Designed a new UI for Google');
insert into notable_skills (applicationId, name, summary) values (351, 'RFLP', 'Managed a team of 20 software interns');
insert into notable_skills (applicationId, name, summary) values (328, 'Hardware Architecture', 'Created a web application that tracks the user''s daily caloric intake');
insert into notable_skills (applicationId, name, summary) values (130, 'Flow Cytometry', 'Managed a team of 20 software interns');
insert into notable_skills (applicationId, name, summary) values (53, 'LDPC', 'Created a web application that tracks the user''s daily caloric intake');
insert into notable_skills (applicationId, name, summary) values (129, 'WLAN', 'Managed a team of 20 software interns');
insert into notable_skills (applicationId, name, summary) values (142, 'OTS', 'Designed a new UI for Google');
insert into notable_skills (applicationId, name, summary) values (57, 'Cash Flow', 'Designed a new UI for Google');
insert into notable_skills (applicationId, name, summary) values (7, 'SAP MM Module', 'Managed a team of 20 software interns');
insert into notable_skills (applicationId, name, summary) values (319, 'CNAS', 'Managed a team of 20 software interns');
insert into notable_skills (applicationId, name, summary) values (493, 'FpML', 'Designed a new UI for Google');
insert into notable_skills (applicationId, name, summary) values (473, 'SNA', 'Developed a new algorithm to predict bitcoin prices');
insert into notable_skills (applicationId, name, summary) values (260, 'XRY', 'Developed a new algorithm to predict bitcoin prices');
insert into notable_skills (applicationId, name, summary) values (354, 'Overseas Experience', 'Managed a team of 20 software interns');
insert into notable_skills (applicationId, name, summary) values (361, 'Dynamics', 'Created a web application that tracks the user''s daily caloric intake');
insert into notable_skills (applicationId, name, summary) values (271, 'Typewriter', 'Created a web application that tracks the user''s daily caloric intake');
insert into notable_skills (applicationId, name, summary) values (452, 'Business Alliances', 'Created a web application that tracks the user''s daily caloric intake');
insert into notable_skills (applicationId, name, summary) values (29, 'DVB-T', 'Created a web application that tracks the user''s daily caloric intake');
insert into notable_skills (applicationId, name, summary) values (310, 'JDA E3', 'Created a web application that tracks the user''s daily caloric intake');
insert into notable_skills (applicationId, name, summary) values (460, 'RELAX NG', 'Designed a new UI for Google');
insert into notable_skills (applicationId, name, summary) values (208, 'Market Risk', 'Managed a team of 20 software interns');
insert into notable_skills (applicationId, name, summary) values (401, 'Healthy Eating', 'Created a web application that tracks the user''s daily caloric intake');
insert into notable_skills (applicationId, name, summary) values (419, 'Chemistry', 'Designed a new UI for Google');
insert into notable_skills (applicationId, name, summary) values (448, 'Book Design', 'Developed a new algorithm to predict bitcoin prices');
insert into notable_skills (applicationId, name, summary) values (62, 'MD&amp;A', 'Designed a new UI for Google');
insert into notable_skills (applicationId, name, summary) values (206, 'Weapons', 'Managed a team of 20 software interns');
insert into notable_skills (applicationId, name, summary) values (417, 'IBM Websphere Commerce', 'Created a web application that tracks the user''s daily caloric intake');
insert into notable_skills (applicationId, name, summary) values (232, 'Group Dynamics', 'Designed a new UI for Google');
insert into notable_skills (applicationId, name, summary) values (197, 'SRED', 'Created a web application that tracks the user''s daily caloric intake');
insert into notable_skills (applicationId, name, summary) values (34, 'eBusiness Suite', 'Created a web application that tracks the user''s daily caloric intake');
insert into notable_skills (applicationId, name, summary) values (316, 'Strategic Alliances', 'Developed a new algorithm to predict bitcoin prices');
insert into notable_skills (applicationId, name, summary) values (61, 'OmniGraffle', 'Developed a new algorithm to predict bitcoin prices');
insert into notable_skills (applicationId, name, summary) values (325, 'Java RMI', 'Managed a team of 20 software interns');
insert into notable_skills (applicationId, name, summary) values (450, 'SRED', 'Developed a new algorithm to predict bitcoin prices');
insert into notable_skills (applicationId, name, summary) values (227, 'TDMA', 'Designed a new UI for Google');
insert into notable_skills (applicationId, name, summary) values (289, 'Life Insurance', 'Created a web application that tracks the user''s daily caloric intake');
insert into notable_skills (applicationId, name, summary) values (183, 'TMS320', 'Created a web application that tracks the user''s daily caloric intake');
insert into notable_skills (applicationId, name, summary) values (214, 'TS', 'Created a web application that tracks the user''s daily caloric intake');
insert into notable_skills (applicationId, name, summary) values (72, 'NBAR', 'Developed a new algorithm to predict bitcoin prices');
insert into notable_skills (applicationId, name, summary) values (438, 'Young Adults', 'Created a web application that tracks the user''s daily caloric intake');
insert into notable_skills (applicationId, name, summary) values (193, 'Vaccines', 'Managed a team of 20 software interns');
insert into notable_skills (applicationId, name, summary) values (49, 'GTD', 'Created a web application that tracks the user''s daily caloric intake');
insert into notable_skills (applicationId, name, summary) values (426, 'FSMS', 'Created a web application that tracks the user''s daily caloric intake');
insert into notable_skills (applicationId, name, summary) values (322, 'Volunteer Training', 'Created a web application that tracks the user''s daily caloric intake');
insert into notable_skills (applicationId, name, summary) values (97, 'Organizational Behavior', 'Developed a new algorithm to predict bitcoin prices');
insert into notable_skills (applicationId, name, summary) values (164, 'OMB Circular A-133', 'Managed a team of 20 software interns');
insert into notable_skills (applicationId, name, summary) values (85, 'High Voltage', 'Designed a new UI for Google');
insert into notable_skills (applicationId, name, summary) values (321, 'VNC', 'Created a web application that tracks the user''s daily caloric intake');
insert into notable_skills (applicationId, name, summary) values (208, 'QC Tools', 'Managed a team of 20 software interns');
insert into notable_skills (applicationId, name, summary) values (138, 'Yeast', 'Designed a new UI for Google');
insert into notable_skills (applicationId, name, summary) values (32, 'PyGTK', 'Developed a new algorithm to predict bitcoin prices');
insert into notable_skills (applicationId, name, summary) values (127, 'FX Swaps', 'Designed a new UI for Google');
insert into notable_skills (applicationId, name, summary) values (430, 'Junior Golf', 'Created a web application that tracks the user''s daily caloric intake');
insert into notable_skills (applicationId, name, summary) values (424, 'TCF', 'Created a web application that tracks the user''s daily caloric intake');
insert into notable_skills (applicationId, name, summary) values (38, 'SSL Certificates', 'Designed a new UI for Google');
insert into notable_skills (applicationId, name, summary) values (224, 'OEM Management', 'Created a web application that tracks the user''s daily caloric intake');
insert into notable_skills (applicationId, name, summary) values (247, 'Swaps', 'Designed a new UI for Google');
insert into notable_skills (applicationId, name, summary) values (160, 'eWFM', 'Created a web application that tracks the user''s daily caloric intake');
insert into notable_skills (applicationId, name, summary) values (318, 'OSHA 30-Hour', 'Managed a team of 20 software interns');
insert into notable_skills (applicationId, name, summary) values (250, 'Flash', 'Created a web application that tracks the user''s daily caloric intake');
insert into notable_skills (applicationId, name, summary) values (280, 'Smart GWT', 'Designed a new UI for Google');
insert into notable_skills (applicationId, name, summary) values (84, 'Yard Work', 'Managed a team of 20 software interns');
insert into notable_skills (applicationId, name, summary) values (21, 'UB92', 'Managed a team of 20 software interns');
insert into notable_skills (applicationId, name, summary) values (139, 'BST', 'Developed a new algorithm to predict bitcoin prices');
insert into notable_skills (applicationId, name, summary) values (435, 'Corporate FP&amp;A', 'Managed a team of 20 software interns');
insert into notable_skills (applicationId, name, summary) values (282, 'BSP', 'Created a web application that tracks the user''s daily caloric intake');
insert into notable_skills (applicationId, name, summary) values (285, 'Townhomes', 'Designed a new UI for Google');
insert into notable_skills (applicationId, name, summary) values (157, 'Ksh', 'Designed a new UI for Google');
insert into notable_skills (applicationId, name, summary) values (338, 'CSCS Card', 'Created a web application that tracks the user''s daily caloric intake');
insert into notable_skills (applicationId, name, summary) values (408, 'Glasses', 'Created a web application that tracks the user''s daily caloric intake');
insert into notable_skills (applicationId, name, summary) values (157, 'SQLite', 'Developed a new algorithm to predict bitcoin prices');
insert into notable_skills (applicationId, name, summary) values (454, 'dSPACE', 'Created a web application that tracks the user''s daily caloric intake');
insert into notable_skills (applicationId, name, summary) values (298, 'MPI', 'Created a web application that tracks the user''s daily caloric intake');
insert into notable_skills (applicationId, name, summary) values (158, 'RMI', 'Managed a team of 20 software interns');
insert into notable_skills (applicationId, name, summary) values (323, 'Java', 'Managed a team of 20 software interns');
insert into notable_skills (applicationId, name, summary) values (197, 'Lyrical', 'Created a web application that tracks the user''s daily caloric intake');
insert into notable_skills (applicationId, name, summary) values (336, 'GNU tools', 'Managed a team of 20 software interns');
insert into notable_skills (applicationId, name, summary) values (430, 'Modeling', 'Developed a new algorithm to predict bitcoin prices');
insert into notable_skills (applicationId, name, summary) values (444, 'IBM Websphere Commerce', 'Designed a new UI for Google');
insert into notable_skills (applicationId, name, summary) values (423, 'Air Force', 'Created a web application that tracks the user''s daily caloric intake');
insert into notable_skills (applicationId, name, summary) values (310, 'MXF', 'Developed a new algorithm to predict bitcoin prices');
insert into notable_skills (applicationId, name, summary) values (16, 'DVB-C', 'Managed a team of 20 software interns');
insert into notable_skills (applicationId, name, summary) values (275, 'VLC', 'Created a web application that tracks the user''s daily caloric intake');
insert into notable_skills (applicationId, name, summary) values (280, 'Affiliate Management', 'Managed a team of 20 software interns');
insert into notable_skills (applicationId, name, summary) values (484, 'Play by Play', 'Created a web application that tracks the user''s daily caloric intake');
insert into notable_skills (applicationId, name, summary) values (94, 'BSSAP', 'Developed a new algorithm to predict bitcoin prices');
insert into notable_skills (applicationId, name, summary) values (51, 'Digital Journalism', 'Created a web application that tracks the user''s daily caloric intake');
insert into notable_skills (applicationId, name, summary) values (384, 'Animal Nutrition', 'Designed a new UI for Google');
insert into notable_skills (applicationId, name, summary) values (388, 'OCLC Connexion', 'Designed a new UI for Google');
insert into notable_skills (applicationId, name, summary) values (485, 'ATP', 'Created a web application that tracks the user''s daily caloric intake');
insert into notable_skills (applicationId, name, summary) values (443, 'EIGRP', 'Developed a new algorithm to predict bitcoin prices');
insert into notable_skills (applicationId, name, summary) values (221, 'Yellow Book', 'Developed a new algorithm to predict bitcoin prices');
insert into notable_skills (applicationId, name, summary) values (165, 'Supply Chain Optimization', 'Designed a new UI for Google');
insert into notable_skills (applicationId, name, summary) values (439, 'Zen Shiatsu', 'Created a web application that tracks the user''s daily caloric intake');
insert into notable_skills (applicationId, name, summary) values (373, 'Human Capital', 'Designed a new UI for Google');
insert into notable_skills (applicationId, name, summary) values (266, 'DNA quantification', 'Designed a new UI for Google');
insert into notable_skills (applicationId, name, summary) values (366, 'Latin America', 'Designed a new UI for Google');
insert into notable_skills (applicationId, name, summary) values (93, 'Published Author', 'Managed a team of 20 software interns');
insert into notable_skills (applicationId, name, summary) values (109, 'IBS', 'Developed a new algorithm to predict bitcoin prices');
insert into notable_skills (applicationId, name, summary) values (358, 'Consumer Electronics', 'Managed a team of 20 software interns');
insert into notable_skills (applicationId, name, summary) values (78, 'CFRA', 'Created a web application that tracks the user''s daily caloric intake');
insert into notable_skills (applicationId, name, summary) values (430, 'PMO Design', 'Developed a new algorithm to predict bitcoin prices');
insert into notable_skills (applicationId, name, summary) values (189, 'TL9000', 'Developed a new algorithm to predict bitcoin prices');
insert into notable_skills (applicationId, name, summary) values (212, 'EMS', 'Managed a team of 20 software interns');
insert into notable_skills (applicationId, name, summary) values (432, 'Portrait Photography', 'Created a web application that tracks the user''s daily caloric intake');
insert into notable_skills (applicationId, name, summary) values (440, 'LDRA', 'Managed a team of 20 software interns');
insert into notable_skills (applicationId, name, summary) values (106, 'Clinical Research', 'Created a web application that tracks the user''s daily caloric intake');
insert into notable_skills (applicationId, name, summary) values (285, 'IT Transformation', 'Designed a new UI for Google');
insert into notable_skills (applicationId, name, summary) values (59, 'CDPE', 'Developed a new algorithm to predict bitcoin prices');
insert into notable_skills (applicationId, name, summary) values (478, 'RS422', 'Designed a new UI for Google');
insert into notable_skills (applicationId, name, summary) values (104, 'Occupational Health Nursing', 'Created a web application that tracks the user''s daily caloric intake');
insert into notable_skills (applicationId, name, summary) values (381, 'CNN Pathfire', 'Designed a new UI for Google');
insert into notable_skills (applicationId, name, summary) values (190, 'Jerseys', 'Developed a new algorithm to predict bitcoin prices');
insert into notable_skills (applicationId, name, summary) values (292, 'Mythology', 'Created a web application that tracks the user''s daily caloric intake');
insert into notable_skills (applicationId, name, summary) values (152, 'Abstracting', 'Designed a new UI for Google');
insert into notable_skills (applicationId, name, summary) values (246, 'Oncology', 'Developed a new algorithm to predict bitcoin prices');
insert into notable_skills (applicationId, name, summary) values (212, 'Events Coordination', 'Created a web application that tracks the user''s daily caloric intake');
insert into notable_skills (applicationId, name, summary) values (280, 'SRED', 'Developed a new algorithm to predict bitcoin prices');
insert into notable_skills (applicationId, name, summary) values (387, 'Human Factors', 'Developed a new algorithm to predict bitcoin prices');
insert into notable_skills (applicationId, name, summary) values (259, 'Process Improvement', 'Created a web application that tracks the user''s daily caloric intake');
insert into notable_skills (applicationId, name, summary) values (348, 'UI Automation', 'Developed a new algorithm to predict bitcoin prices');
insert into notable_skills (applicationId, name, summary) values (408, 'Electrical Engineering', 'Designed a new UI for Google');
insert into notable_skills (applicationId, name, summary) values (479, 'Gel Electrophoresis', 'Managed a team of 20 software interns');
insert into notable_skills (applicationId, name, summary) values (306, 'DTE', 'Created a web application that tracks the user''s daily caloric intake');
insert into notable_skills (applicationId, name, summary) values (469, 'MC2', 'Managed a team of 20 software interns');
insert into notable_skills (applicationId, name, summary) values (319, 'TCP', 'Designed a new UI for Google');
insert into notable_skills (applicationId, name, summary) values (51, 'Smart Metering', 'Developed a new algorithm to predict bitcoin prices');
insert into notable_skills (applicationId, name, summary) values (191, 'Mood Boards', 'Managed a team of 20 software interns');
insert into notable_skills (applicationId, name, summary) values (233, 'Siebel', 'Managed a team of 20 software interns');
insert into notable_skills (applicationId, name, summary) values (393, 'Environmental Policy', 'Managed a team of 20 software interns');
insert into notable_skills (applicationId, name, summary) values (491, 'XSL', 'Developed a new algorithm to predict bitcoin prices');
insert into notable_skills (applicationId, name, summary) values (41, 'WML', 'Created a web application that tracks the user''s daily caloric intake');
insert into notable_skills (applicationId, name, summary) values (38, 'Pay TV', 'Designed a new UI for Google');
insert into notable_skills (applicationId, name, summary) values (329, 'Juniper JNCIA', 'Created a web application that tracks the user''s daily caloric intake');
insert into notable_skills (applicationId, name, summary) values (390, 'Cinematography', 'Created a web application that tracks the user''s daily caloric intake');
insert into notable_skills (applicationId, name, summary) values (120, 'IVIG', 'Managed a team of 20 software interns');
insert into notable_skills (applicationId, name, summary) values (72, 'USDA', 'Created a web application that tracks the user''s daily caloric intake');
insert into notable_skills (applicationId, name, summary) values (403, 'gSOAP', 'Designed a new UI for Google');
insert into notable_skills (applicationId, name, summary) values (227, 'Storage', 'Designed a new UI for Google');
insert into notable_skills (applicationId, name, summary) values (262, 'Corporate Tax', 'Managed a team of 20 software interns');
insert into notable_skills (applicationId, name, summary) values (197, 'XDoclet', 'Created a web application that tracks the user''s daily caloric intake');
insert into notable_skills (applicationId, name, summary) values (382, 'Fitness', 'Designed a new UI for Google');
insert into notable_skills (applicationId, name, summary) values (323, 'Food Industry', 'Designed a new UI for Google');
insert into notable_skills (applicationId, name, summary) values (269, 'Lesson Planning', 'Created a web application that tracks the user''s daily caloric intake');
insert into notable_skills (applicationId, name, summary) values (87, 'Ion Channels', 'Developed a new algorithm to predict bitcoin prices');
insert into notable_skills (applicationId, name, summary) values (294, 'pgAdmin', 'Developed a new algorithm to predict bitcoin prices');
insert into notable_skills (applicationId, name, summary) values (429, 'National Association of Realtors', 'Created a web application that tracks the user''s daily caloric intake');
insert into notable_skills (applicationId, name, summary) values (9, 'Brochures', 'Designed a new UI for Google');
insert into notable_skills (applicationId, name, summary) values (241, 'HLASM', 'Developed a new algorithm to predict bitcoin prices');
insert into notable_skills (applicationId, name, summary) values (167, 'CTFL', 'Created a web application that tracks the user''s daily caloric intake');
insert into notable_skills (applicationId, name, summary) values (119, 'Fashion Shows', 'Created a web application that tracks the user''s daily caloric intake');
insert into notable_skills (applicationId, name, summary) values (253, 'RMI', 'Developed a new algorithm to predict bitcoin prices');
insert into notable_skills (applicationId, name, summary) values (322, 'MBD', 'Developed a new algorithm to predict bitcoin prices');
insert into notable_skills (applicationId, name, summary) values (168, 'Start-up Consulting', 'Managed a team of 20 software interns');
insert into notable_skills (applicationId, name, summary) values (444, 'Study Abroad Programs', 'Designed a new UI for Google');
insert into notable_skills (applicationId, name, summary) values (308, 'XMLBeans', 'Created a web application that tracks the user''s daily caloric intake');
insert into notable_skills (applicationId, name, summary) values (123, 'RFID Applications', 'Created a web application that tracks the user''s daily caloric intake');
insert into notable_skills (applicationId, name, summary) values (326, 'User Experience', 'Developed a new algorithm to predict bitcoin prices');
insert into notable_skills (applicationId, name, summary) values (274, 'Auditing', 'Designed a new UI for Google');
insert into notable_skills (applicationId, name, summary) values (360, 'HLSL', 'Created a web application that tracks the user''s daily caloric intake');
insert into notable_skills (applicationId, name, summary) values (499, 'Make vs Buy', 'Managed a team of 20 software interns');
insert into notable_skills (applicationId, name, summary) values (424, 'TMF', 'Created a web application that tracks the user''s daily caloric intake');
insert into notable_skills (applicationId, name, summary) values (251, 'Business Intelligence', 'Managed a team of 20 software interns');
insert into notable_skills (applicationId, name, summary) values (332, 'Case Management', 'Developed a new algorithm to predict bitcoin prices');
insert into notable_skills (applicationId, name, summary) values (155, 'BDCs', 'Managed a team of 20 software interns');
insert into notable_skills (applicationId, name, summary) values (121, 'IATSE', 'Created a web application that tracks the user''s daily caloric intake');
insert into notable_skills (applicationId, name, summary) values (363, 'Ownership', 'Managed a team of 20 software interns');
insert into notable_skills (applicationId, name, summary) values (97, 'SSCP', 'Developed a new algorithm to predict bitcoin prices');
insert into notable_skills (applicationId, name, summary) values (225, 'MCNP', 'Developed a new algorithm to predict bitcoin prices');
insert into notable_skills (applicationId, name, summary) values (246, 'Psychometrics', 'Managed a team of 20 software interns');
insert into notable_skills (applicationId, name, summary) values (440, 'Oncology', 'Created a web application that tracks the user''s daily caloric intake');
insert into notable_skills (applicationId, name, summary) values (252, 'AOI', 'Designed a new UI for Google');
insert into notable_skills (applicationId, name, summary) values (394, 'Professional Services', 'Developed a new algorithm to predict bitcoin prices');
insert into notable_skills (applicationId, name, summary) values (223, 'Flatbed', 'Created a web application that tracks the user''s daily caloric intake');
