USE cosint;

-- mock data for related coursework
insert into related_coursework (applicationId, name, summary) values (231, 'Logic and Computation', 'Focus on database management and design');
insert into related_coursework (applicationId, name, summary) values (337, 'Human Computer Interactions', 'Focused on the development pipeline of applications');
insert into related_coursework (applicationId, name, summary) values (68, 'Fundamentals of Software Engineering', 'Applied multiple high level algorithms to solve real world problems');
insert into related_coursework (applicationId, name, summary) values (301, 'Fundamentals of Software Engineering', 'Designed complex objects to develop web applications');
insert into related_coursework (applicationId, name, summary) values (383, 'Algorithms and Data', 'Designed complex objects to develop web applications');
insert into related_coursework (applicationId, name, summary) values (88, 'Logic and Computation', 'Focused on the development pipeline of applications');
insert into related_coursework (applicationId, name, summary) values (171, 'Algorithms and Data', 'Designed complex objects to develop web applications');
insert into related_coursework (applicationId, name, summary) values (160, 'Logic and Computation', 'Designed complex objects to develop web applications');
insert into related_coursework (applicationId, name, summary) values (60, 'Advanced Database Systems', 'Focused on the development pipeline of applications');
insert into related_coursework (applicationId, name, summary) values (390, 'Human Computer Interactions', 'Focus on database management and design');
insert into related_coursework (applicationId, name, summary) values (312, 'Algorithms and Data', 'Applied multiple high level algorithms to solve real world problems');
insert into related_coursework (applicationId, name, summary) values (217, 'Human Computer Interactions', 'Designed complex objects to develop web applications');
insert into related_coursework (applicationId, name, summary) values (170, 'Object-Oriented Design', 'Focus on database management and design');
insert into related_coursework (applicationId, name, summary) values (171, 'Logic and Computation', 'Designed complex objects to develop web applications');
insert into related_coursework (applicationId, name, summary) values (26, 'Human Computer Interactions', 'Designed complex objects to develop web applications');
insert into related_coursework (applicationId, name, summary) values (381, 'Object-Oriented Design', 'Applied multiple high level algorithms to solve real world problems');
insert into related_coursework (applicationId, name, summary) values (167, 'Logic and Computation', 'Designed complex objects to develop web applications');
insert into related_coursework (applicationId, name, summary) values (219, 'Fundamentals of Software Engineering', 'Focused on the development pipeline of applications');
insert into related_coursework (applicationId, name, summary) values (282, 'Human Computer Interactions', 'Focus on database management and design');
insert into related_coursework (applicationId, name, summary) values (296, 'Logic and Computation', 'Focus on database management and design');
insert into related_coursework (applicationId, name, summary) values (126, 'Algorithms and Data', 'Focus on database management and design');
insert into related_coursework (applicationId, name, summary) values (413, 'Human Computer Interactions', 'Focus on database management and design');
insert into related_coursework (applicationId, name, summary) values (318, 'Advanced Database Systems', 'Designed complex objects to develop web applications');
insert into related_coursework (applicationId, name, summary) values (152, 'Advanced Database Systems', 'Focused on the development pipeline of applications');
insert into related_coursework (applicationId, name, summary) values (93, 'Fundamentals of Software Engineering', 'Focus on database management and design');
insert into related_coursework (applicationId, name, summary) values (41, 'Logic and Computation', 'Focused on the development pipeline of applications');
insert into related_coursework (applicationId, name, summary) values (92, 'Advanced Database Systems', 'Applied multiple high level algorithms to solve real world problems');
insert into related_coursework (applicationId, name, summary) values (368, 'Object-Oriented Design', 'Focused on the development pipeline of applications');
insert into related_coursework (applicationId, name, summary) values (271, 'Advanced Database Systems', 'Focused on the development pipeline of applications');
insert into related_coursework (applicationId, name, summary) values (172, 'Fundamentals of Software Engineering', 'Focus on database management and design');
insert into related_coursework (applicationId, name, summary) values (345, 'Logic and Computation', 'Focused on the development pipeline of applications');
insert into related_coursework (applicationId, name, summary) values (419, 'Fundamentals of Software Engineering', 'Focused on the development pipeline of applications');
insert into related_coursework (applicationId, name, summary) values (17, 'Advanced Database Systems', 'Focus on database management and design');
insert into related_coursework (applicationId, name, summary) values (299, 'Algorithms and Data', 'Focus on database management and design');
insert into related_coursework (applicationId, name, summary) values (89, 'Object-Oriented Design', 'Applied multiple high level algorithms to solve real world problems');
insert into related_coursework (applicationId, name, summary) values (348, 'Human Computer Interactions', 'Focus on database management and design');
insert into related_coursework (applicationId, name, summary) values (357, 'Logic and Computation', 'Designed complex objects to develop web applications');
insert into related_coursework (applicationId, name, summary) values (271, 'Logic and Computation', 'Applied multiple high level algorithms to solve real world problems');
insert into related_coursework (applicationId, name, summary) values (133, 'Logic and Computation', 'Designed complex objects to develop web applications');
insert into related_coursework (applicationId, name, summary) values (49, 'Logic and Computation', 'Focused on the development pipeline of applications');
insert into related_coursework (applicationId, name, summary) values (49, 'Human Computer Interactions', 'Designed complex objects to develop web applications');
insert into related_coursework (applicationId, name, summary) values (217, 'Fundamentals of Software Engineering', 'Focused on the development pipeline of applications');
insert into related_coursework (applicationId, name, summary) values (143, 'Advanced Database Systems', 'Focused on the development pipeline of applications');
insert into related_coursework (applicationId, name, summary) values (19, 'Human Computer Interactions', 'Designed complex objects to develop web applications');
insert into related_coursework (applicationId, name, summary) values (247, 'Advanced Database Systems', 'Focus on database management and design');
insert into related_coursework (applicationId, name, summary) values (250, 'Fundamentals of Software Engineering', 'Designed complex objects to develop web applications');
insert into related_coursework (applicationId, name, summary) values (70, 'Object-Oriented Design', 'Designed complex objects to develop web applications');
insert into related_coursework (applicationId, name, summary) values (386, 'Object-Oriented Design', 'Focused on the development pipeline of applications');
insert into related_coursework (applicationId, name, summary) values (261, 'Object-Oriented Design', 'Designed complex objects to develop web applications');
insert into related_coursework (applicationId, name, summary) values (241, 'Algorithms and Data', 'Applied multiple high level algorithms to solve real world problems');
insert into related_coursework (applicationId, name, summary) values (438, 'Fundamentals of Software Engineering', 'Designed complex objects to develop web applications');
insert into related_coursework (applicationId, name, summary) values (43, 'Logic and Computation', 'Designed complex objects to develop web applications');
insert into related_coursework (applicationId, name, summary) values (351, 'Logic and Computation', 'Applied multiple high level algorithms to solve real world problems');
insert into related_coursework (applicationId, name, summary) values (396, 'Human Computer Interactions', 'Focus on database management and design');
insert into related_coursework (applicationId, name, summary) values (279, 'Advanced Database Systems', 'Focus on database management and design');
insert into related_coursework (applicationId, name, summary) values (29, 'Fundamentals of Software Engineering', 'Focused on the development pipeline of applications');
insert into related_coursework (applicationId, name, summary) values (36, 'Advanced Database Systems', 'Focused on the development pipeline of applications');
insert into related_coursework (applicationId, name, summary) values (475, 'Algorithms and Data', 'Applied multiple high level algorithms to solve real world problems');
insert into related_coursework (applicationId, name, summary) values (345, 'Fundamentals of Software Engineering', 'Designed complex objects to develop web applications');
insert into related_coursework (applicationId, name, summary) values (7, 'Object-Oriented Design', 'Focused on the development pipeline of applications');
insert into related_coursework (applicationId, name, summary) values (235, 'Algorithms and Data', 'Applied multiple high level algorithms to solve real world problems');
insert into related_coursework (applicationId, name, summary) values (27, 'Object-Oriented Design', 'Focused on the development pipeline of applications');
insert into related_coursework (applicationId, name, summary) values (403, 'Advanced Database Systems', 'Applied multiple high level algorithms to solve real world problems');
insert into related_coursework (applicationId, name, summary) values (314, 'Object-Oriented Design', 'Applied multiple high level algorithms to solve real world problems');
insert into related_coursework (applicationId, name, summary) values (195, 'Algorithms and Data', 'Designed complex objects to develop web applications');
insert into related_coursework (applicationId, name, summary) values (363, 'Advanced Database Systems', 'Focus on database management and design');
insert into related_coursework (applicationId, name, summary) values (268, 'Fundamentals of Software Engineering', 'Focused on the development pipeline of applications');
insert into related_coursework (applicationId, name, summary) values (264, 'Logic and Computation', 'Designed complex objects to develop web applications');
insert into related_coursework (applicationId, name, summary) values (84, 'Logic and Computation', 'Designed complex objects to develop web applications');
insert into related_coursework (applicationId, name, summary) values (495, 'Object-Oriented Design', 'Applied multiple high level algorithms to solve real world problems');
insert into related_coursework (applicationId, name, summary) values (466, 'Advanced Database Systems', 'Applied multiple high level algorithms to solve real world problems');
insert into related_coursework (applicationId, name, summary) values (274, 'Algorithms and Data', 'Designed complex objects to develop web applications');
insert into related_coursework (applicationId, name, summary) values (495, 'Human Computer Interactions', 'Focus on database management and design');
insert into related_coursework (applicationId, name, summary) values (323, 'Human Computer Interactions', 'Focused on the development pipeline of applications');
insert into related_coursework (applicationId, name, summary) values (495, 'Logic and Computation', 'Focus on database management and design');
insert into related_coursework (applicationId, name, summary) values (361, 'Fundamentals of Software Engineering', 'Focused on the development pipeline of applications');
insert into related_coursework (applicationId, name, summary) values (422, 'Object-Oriented Design', 'Focused on the development pipeline of applications');
insert into related_coursework (applicationId, name, summary) values (195, 'Advanced Database Systems', 'Applied multiple high level algorithms to solve real world problems');
insert into related_coursework (applicationId, name, summary) values (285, 'Advanced Database Systems', 'Applied multiple high level algorithms to solve real world problems');
insert into related_coursework (applicationId, name, summary) values (493, 'Fundamentals of Software Engineering', 'Designed complex objects to develop web applications');
insert into related_coursework (applicationId, name, summary) values (436, 'Object-Oriented Design', 'Designed complex objects to develop web applications');
insert into related_coursework (applicationId, name, summary) values (4, 'Logic and Computation', 'Designed complex objects to develop web applications');
insert into related_coursework (applicationId, name, summary) values (208, 'Advanced Database Systems', 'Applied multiple high level algorithms to solve real world problems');
insert into related_coursework (applicationId, name, summary) values (285, 'Logic and Computation', 'Designed complex objects to develop web applications');
insert into related_coursework (applicationId, name, summary) values (89, 'Algorithms and Data', 'Focus on database management and design');
insert into related_coursework (applicationId, name, summary) values (491, 'Fundamentals of Software Engineering', 'Applied multiple high level algorithms to solve real world problems');
insert into related_coursework (applicationId, name, summary) values (305, 'Algorithms and Data', 'Designed complex objects to develop web applications');
insert into related_coursework (applicationId, name, summary) values (392, 'Advanced Database Systems', 'Focus on database management and design');
insert into related_coursework (applicationId, name, summary) values (148, 'Advanced Database Systems', 'Focus on database management and design');
insert into related_coursework (applicationId, name, summary) values (391, 'Algorithms and Data', 'Designed complex objects to develop web applications');
insert into related_coursework (applicationId, name, summary) values (260, 'Advanced Database Systems', 'Designed complex objects to develop web applications');
insert into related_coursework (applicationId, name, summary) values (353, 'Object-Oriented Design', 'Focus on database management and design');
insert into related_coursework (applicationId, name, summary) values (48, 'Logic and Computation', 'Applied multiple high level algorithms to solve real world problems');
insert into related_coursework (applicationId, name, summary) values (260, 'Logic and Computation', 'Focused on the development pipeline of applications');
insert into related_coursework (applicationId, name, summary) values (420, 'Fundamentals of Software Engineering', 'Applied multiple high level algorithms to solve real world problems');
insert into related_coursework (applicationId, name, summary) values (487, 'Advanced Database Systems', 'Applied multiple high level algorithms to solve real world problems');
insert into related_coursework (applicationId, name, summary) values (457, 'Object-Oriented Design', 'Applied multiple high level algorithms to solve real world problems');
insert into related_coursework (applicationId, name, summary) values (80, 'Advanced Database Systems', 'Focused on the development pipeline of applications');
insert into related_coursework (applicationId, name, summary) values (85, 'Logic and Computation', 'Focused on the development pipeline of applications');
insert into related_coursework (applicationId, name, summary) values (413, 'Object-Oriented Design', 'Designed complex objects to develop web applications');
insert into related_coursework (applicationId, name, summary) values (433, 'Advanced Database Systems', 'Designed complex objects to develop web applications');
insert into related_coursework (applicationId, name, summary) values (4, 'Object-Oriented Design', 'Designed complex objects to develop web applications');
insert into related_coursework (applicationId, name, summary) values (76, 'Fundamentals of Software Engineering', 'Focused on the development pipeline of applications');
insert into related_coursework (applicationId, name, summary) values (201, 'Algorithms and Data', 'Designed complex objects to develop web applications');
insert into related_coursework (applicationId, name, summary) values (459, 'Logic and Computation', 'Focused on the development pipeline of applications');
insert into related_coursework (applicationId, name, summary) values (466, 'Algorithms and Data', 'Focused on the development pipeline of applications');
insert into related_coursework (applicationId, name, summary) values (373, 'Logic and Computation', 'Focus on database management and design');
insert into related_coursework (applicationId, name, summary) values (246, 'Advanced Database Systems', 'Focus on database management and design');
insert into related_coursework (applicationId, name, summary) values (236, 'Logic and Computation', 'Applied multiple high level algorithms to solve real world problems');
insert into related_coursework (applicationId, name, summary) values (304, 'Algorithms and Data', 'Focus on database management and design');
insert into related_coursework (applicationId, name, summary) values (199, 'Logic and Computation', 'Designed complex objects to develop web applications');
insert into related_coursework (applicationId, name, summary) values (283, 'Advanced Database Systems', 'Focused on the development pipeline of applications');
insert into related_coursework (applicationId, name, summary) values (211, 'Algorithms and Data', 'Focused on the development pipeline of applications');
insert into related_coursework (applicationId, name, summary) values (64, 'Object-Oriented Design', 'Applied multiple high level algorithms to solve real world problems');
insert into related_coursework (applicationId, name, summary) values (4, 'Human Computer Interactions', 'Designed complex objects to develop web applications');
insert into related_coursework (applicationId, name, summary) values (79, 'Object-Oriented Design', 'Designed complex objects to develop web applications');
insert into related_coursework (applicationId, name, summary) values (431, 'Human Computer Interactions', 'Focus on database management and design');
insert into related_coursework (applicationId, name, summary) values (32, 'Advanced Database Systems', 'Focused on the development pipeline of applications');
insert into related_coursework (applicationId, name, summary) values (383, 'Object-Oriented Design', 'Applied multiple high level algorithms to solve real world problems');
insert into related_coursework (applicationId, name, summary) values (399, 'Human Computer Interactions', 'Applied multiple high level algorithms to solve real world problems');
insert into related_coursework (applicationId, name, summary) values (75, 'Fundamentals of Software Engineering', 'Focused on the development pipeline of applications');
insert into related_coursework (applicationId, name, summary) values (220, 'Human Computer Interactions', 'Applied multiple high level algorithms to solve real world problems');
insert into related_coursework (applicationId, name, summary) values (282, 'Object-Oriented Design', 'Applied multiple high level algorithms to solve real world problems');
insert into related_coursework (applicationId, name, summary) values (311, 'Advanced Database Systems', 'Designed complex objects to develop web applications');
insert into related_coursework (applicationId, name, summary) values (114, 'Logic and Computation', 'Focused on the development pipeline of applications');
insert into related_coursework (applicationId, name, summary) values (124, 'Human Computer Interactions', 'Focused on the development pipeline of applications');
insert into related_coursework (applicationId, name, summary) values (297, 'Fundamentals of Software Engineering', 'Focus on database management and design');
insert into related_coursework (applicationId, name, summary) values (387, 'Algorithms and Data', 'Applied multiple high level algorithms to solve real world problems');
insert into related_coursework (applicationId, name, summary) values (406, 'Human Computer Interactions', 'Focused on the development pipeline of applications');
insert into related_coursework (applicationId, name, summary) values (398, 'Fundamentals of Software Engineering', 'Designed complex objects to develop web applications');
insert into related_coursework (applicationId, name, summary) values (73, 'Logic and Computation', 'Focused on the development pipeline of applications');
insert into related_coursework (applicationId, name, summary) values (350, 'Object-Oriented Design', 'Designed complex objects to develop web applications');
insert into related_coursework (applicationId, name, summary) values (124, 'Human Computer Interactions', 'Focus on database management and design');
insert into related_coursework (applicationId, name, summary) values (168, 'Algorithms and Data', 'Focused on the development pipeline of applications');
insert into related_coursework (applicationId, name, summary) values (351, 'Human Computer Interactions', 'Designed complex objects to develop web applications');
insert into related_coursework (applicationId, name, summary) values (190, 'Object-Oriented Design', 'Applied multiple high level algorithms to solve real world problems');
insert into related_coursework (applicationId, name, summary) values (438, 'Logic and Computation', 'Applied multiple high level algorithms to solve real world problems');
insert into related_coursework (applicationId, name, summary) values (287, 'Advanced Database Systems', 'Applied multiple high level algorithms to solve real world problems');
insert into related_coursework (applicationId, name, summary) values (23, 'Object-Oriented Design', 'Applied multiple high level algorithms to solve real world problems');
insert into related_coursework (applicationId, name, summary) values (500, 'Human Computer Interactions', 'Applied multiple high level algorithms to solve real world problems');
insert into related_coursework (applicationId, name, summary) values (247, 'Object-Oriented Design', 'Designed complex objects to develop web applications');
insert into related_coursework (applicationId, name, summary) values (13, 'Fundamentals of Software Engineering', 'Designed complex objects to develop web applications');
insert into related_coursework (applicationId, name, summary) values (91, 'Fundamentals of Software Engineering', 'Focus on database management and design');
insert into related_coursework (applicationId, name, summary) values (309, 'Algorithms and Data', 'Applied multiple high level algorithms to solve real world problems');
insert into related_coursework (applicationId, name, summary) values (235, 'Advanced Database Systems', 'Focus on database management and design');
insert into related_coursework (applicationId, name, summary) values (467, 'Object-Oriented Design', 'Applied multiple high level algorithms to solve real world problems');
insert into related_coursework (applicationId, name, summary) values (122, 'Fundamentals of Software Engineering', 'Focus on database management and design');
insert into related_coursework (applicationId, name, summary) values (304, 'Human Computer Interactions', 'Designed complex objects to develop web applications');
insert into related_coursework (applicationId, name, summary) values (156, 'Human Computer Interactions', 'Designed complex objects to develop web applications');
insert into related_coursework (applicationId, name, summary) values (200, 'Logic and Computation', 'Designed complex objects to develop web applications');
insert into related_coursework (applicationId, name, summary) values (74, 'Advanced Database Systems', 'Applied multiple high level algorithms to solve real world problems');
insert into related_coursework (applicationId, name, summary) values (324, 'Logic and Computation', 'Designed complex objects to develop web applications');
insert into related_coursework (applicationId, name, summary) values (389, 'Object-Oriented Design', 'Focused on the development pipeline of applications');
insert into related_coursework (applicationId, name, summary) values (81, 'Human Computer Interactions', 'Focused on the development pipeline of applications');
insert into related_coursework (applicationId, name, summary) values (382, 'Advanced Database Systems', 'Focused on the development pipeline of applications');
insert into related_coursework (applicationId, name, summary) values (104, 'Fundamentals of Software Engineering', 'Designed complex objects to develop web applications');
insert into related_coursework (applicationId, name, summary) values (367, 'Fundamentals of Software Engineering', 'Applied multiple high level algorithms to solve real world problems');
insert into related_coursework (applicationId, name, summary) values (499, 'Algorithms and Data', 'Focused on the development pipeline of applications');
insert into related_coursework (applicationId, name, summary) values (369, 'Fundamentals of Software Engineering', 'Focused on the development pipeline of applications');
insert into related_coursework (applicationId, name, summary) values (120, 'Human Computer Interactions', 'Applied multiple high level algorithms to solve real world problems');
insert into related_coursework (applicationId, name, summary) values (86, 'Logic and Computation', 'Designed complex objects to develop web applications');
insert into related_coursework (applicationId, name, summary) values (282, 'Advanced Database Systems', 'Focus on database management and design');
insert into related_coursework (applicationId, name, summary) values (474, 'Human Computer Interactions', 'Focused on the development pipeline of applications');
insert into related_coursework (applicationId, name, summary) values (142, 'Human Computer Interactions', 'Applied multiple high level algorithms to solve real world problems');
insert into related_coursework (applicationId, name, summary) values (168, 'Object-Oriented Design', 'Focus on database management and design');
insert into related_coursework (applicationId, name, summary) values (431, 'Advanced Database Systems', 'Designed complex objects to develop web applications');
insert into related_coursework (applicationId, name, summary) values (477, 'Advanced Database Systems', 'Designed complex objects to develop web applications');
insert into related_coursework (applicationId, name, summary) values (56, 'Fundamentals of Software Engineering', 'Applied multiple high level algorithms to solve real world problems');
insert into related_coursework (applicationId, name, summary) values (492, 'Object-Oriented Design', 'Applied multiple high level algorithms to solve real world problems');
insert into related_coursework (applicationId, name, summary) values (50, 'Human Computer Interactions', 'Applied multiple high level algorithms to solve real world problems');
insert into related_coursework (applicationId, name, summary) values (202, 'Advanced Database Systems', 'Focused on the development pipeline of applications');
insert into related_coursework (applicationId, name, summary) values (355, 'Fundamentals of Software Engineering', 'Focused on the development pipeline of applications');
insert into related_coursework (applicationId, name, summary) values (366, 'Logic and Computation', 'Designed complex objects to develop web applications');
insert into related_coursework (applicationId, name, summary) values (98, 'Logic and Computation', 'Applied multiple high level algorithms to solve real world problems');
insert into related_coursework (applicationId, name, summary) values (259, 'Algorithms and Data', 'Focus on database management and design');
insert into related_coursework (applicationId, name, summary) values (497, 'Human Computer Interactions', 'Designed complex objects to develop web applications');
insert into related_coursework (applicationId, name, summary) values (144, 'Object-Oriented Design', 'Focus on database management and design');
insert into related_coursework (applicationId, name, summary) values (133, 'Object-Oriented Design', 'Focus on database management and design');
insert into related_coursework (applicationId, name, summary) values (231, 'Logic and Computation', 'Focus on database management and design');
insert into related_coursework (applicationId, name, summary) values (121, 'Object-Oriented Design', 'Designed complex objects to develop web applications');
insert into related_coursework (applicationId, name, summary) values (58, 'Algorithms and Data', 'Focus on database management and design');
insert into related_coursework (applicationId, name, summary) values (349, 'Logic and Computation', 'Focused on the development pipeline of applications');
insert into related_coursework (applicationId, name, summary) values (325, 'Algorithms and Data', 'Focused on the development pipeline of applications');
insert into related_coursework (applicationId, name, summary) values (489, 'Fundamentals of Software Engineering', 'Applied multiple high level algorithms to solve real world problems');
insert into related_coursework (applicationId, name, summary) values (275, 'Human Computer Interactions', 'Applied multiple high level algorithms to solve real world problems');
insert into related_coursework (applicationId, name, summary) values (11, 'Advanced Database Systems', 'Focused on the development pipeline of applications');
insert into related_coursework (applicationId, name, summary) values (426, 'Algorithms and Data', 'Applied multiple high level algorithms to solve real world problems');
insert into related_coursework (applicationId, name, summary) values (485, 'Fundamentals of Software Engineering', 'Focus on database management and design');
insert into related_coursework (applicationId, name, summary) values (292, 'Object-Oriented Design', 'Applied multiple high level algorithms to solve real world problems');
insert into related_coursework (applicationId, name, summary) values (182, 'Logic and Computation', 'Focused on the development pipeline of applications');
insert into related_coursework (applicationId, name, summary) values (37, 'Human Computer Interactions', 'Applied multiple high level algorithms to solve real world problems');
insert into related_coursework (applicationId, name, summary) values (76, 'Advanced Database Systems', 'Focused on the development pipeline of applications');
insert into related_coursework (applicationId, name, summary) values (241, 'Fundamentals of Software Engineering', 'Focused on the development pipeline of applications');
insert into related_coursework (applicationId, name, summary) values (395, 'Human Computer Interactions', 'Focused on the development pipeline of applications');
insert into related_coursework (applicationId, name, summary) values (457, 'Algorithms and Data', 'Focus on database management and design');
insert into related_coursework (applicationId, name, summary) values (132, 'Algorithms and Data', 'Focused on the development pipeline of applications');
insert into related_coursework (applicationId, name, summary) values (1, 'Algorithms and Data', 'Focused on the development pipeline of applications');
insert into related_coursework (applicationId, name, summary) values (65, 'Object-Oriented Design', 'Focused on the development pipeline of applications');
insert into related_coursework (applicationId, name, summary) values (155, 'Algorithms and Data', 'Applied multiple high level algorithms to solve real world problems');
insert into related_coursework (applicationId, name, summary) values (132, 'Fundamentals of Software Engineering', 'Applied multiple high level algorithms to solve real world problems');
insert into related_coursework (applicationId, name, summary) values (217, 'Advanced Database Systems', 'Focus on database management and design');
insert into related_coursework (applicationId, name, summary) values (356, 'Object-Oriented Design', 'Focused on the development pipeline of applications');
insert into related_coursework (applicationId, name, summary) values (203, 'Advanced Database Systems', 'Focused on the development pipeline of applications');
insert into related_coursework (applicationId, name, summary) values (367, 'Fundamentals of Software Engineering', 'Designed complex objects to develop web applications');
insert into related_coursework (applicationId, name, summary) values (340, 'Fundamentals of Software Engineering', 'Focus on database management and design');
insert into related_coursework (applicationId, name, summary) values (338, 'Logic and Computation', 'Focus on database management and design');
insert into related_coursework (applicationId, name, summary) values (478, 'Logic and Computation', 'Designed complex objects to develop web applications');
insert into related_coursework (applicationId, name, summary) values (95, 'Algorithms and Data', 'Focused on the development pipeline of applications');
insert into related_coursework (applicationId, name, summary) values (58, 'Fundamentals of Software Engineering', 'Applied multiple high level algorithms to solve real world problems');
insert into related_coursework (applicationId, name, summary) values (442, 'Human Computer Interactions', 'Focused on the development pipeline of applications');
insert into related_coursework (applicationId, name, summary) values (88, 'Advanced Database Systems', 'Focus on database management and design');
insert into related_coursework (applicationId, name, summary) values (423, 'Logic and Computation', 'Applied multiple high level algorithms to solve real world problems');
insert into related_coursework (applicationId, name, summary) values (134, 'Advanced Database Systems', 'Designed complex objects to develop web applications');
insert into related_coursework (applicationId, name, summary) values (184, 'Fundamentals of Software Engineering', 'Applied multiple high level algorithms to solve real world problems');
insert into related_coursework (applicationId, name, summary) values (368, 'Logic and Computation', 'Focus on database management and design');
insert into related_coursework (applicationId, name, summary) values (361, 'Logic and Computation', 'Designed complex objects to develop web applications');
insert into related_coursework (applicationId, name, summary) values (408, 'Fundamentals of Software Engineering', 'Designed complex objects to develop web applications');
insert into related_coursework (applicationId, name, summary) values (55, 'Logic and Computation', 'Designed complex objects to develop web applications');
insert into related_coursework (applicationId, name, summary) values (253, 'Logic and Computation', 'Focus on database management and design');
insert into related_coursework (applicationId, name, summary) values (151, 'Logic and Computation', 'Focused on the development pipeline of applications');
insert into related_coursework (applicationId, name, summary) values (117, 'Object-Oriented Design', 'Focused on the development pipeline of applications');
insert into related_coursework (applicationId, name, summary) values (365, 'Fundamentals of Software Engineering', 'Designed complex objects to develop web applications');
insert into related_coursework (applicationId, name, summary) values (406, 'Algorithms and Data', 'Applied multiple high level algorithms to solve real world problems');
insert into related_coursework (applicationId, name, summary) values (63, 'Human Computer Interactions', 'Focus on database management and design');
insert into related_coursework (applicationId, name, summary) values (351, 'Logic and Computation', 'Applied multiple high level algorithms to solve real world problems');
insert into related_coursework (applicationId, name, summary) values (265, 'Human Computer Interactions', 'Focused on the development pipeline of applications');
insert into related_coursework (applicationId, name, summary) values (317, 'Object-Oriented Design', 'Focus on database management and design');
insert into related_coursework (applicationId, name, summary) values (492, 'Human Computer Interactions', 'Focus on database management and design');
insert into related_coursework (applicationId, name, summary) values (2, 'Algorithms and Data', 'Focused on the development pipeline of applications');
insert into related_coursework (applicationId, name, summary) values (420, 'Human Computer Interactions', 'Focus on database management and design');
insert into related_coursework (applicationId, name, summary) values (127, 'Object-Oriented Design', 'Focused on the development pipeline of applications');
insert into related_coursework (applicationId, name, summary) values (482, 'Human Computer Interactions', 'Focus on database management and design');
insert into related_coursework (applicationId, name, summary) values (260, 'Fundamentals of Software Engineering', 'Focused on the development pipeline of applications');
insert into related_coursework (applicationId, name, summary) values (124, 'Fundamentals of Software Engineering', 'Designed complex objects to develop web applications');
insert into related_coursework (applicationId, name, summary) values (262, 'Algorithms and Data', 'Focus on database management and design');
insert into related_coursework (applicationId, name, summary) values (413, 'Object-Oriented Design', 'Applied multiple high level algorithms to solve real world problems');
insert into related_coursework (applicationId, name, summary) values (481, 'Algorithms and Data', 'Focus on database management and design');
insert into related_coursework (applicationId, name, summary) values (496, 'Algorithms and Data', 'Applied multiple high level algorithms to solve real world problems');
insert into related_coursework (applicationId, name, summary) values (64, 'Logic and Computation', 'Focused on the development pipeline of applications');
insert into related_coursework (applicationId, name, summary) values (454, 'Logic and Computation', 'Applied multiple high level algorithms to solve real world problems');
insert into related_coursework (applicationId, name, summary) values (189, 'Advanced Database Systems', 'Applied multiple high level algorithms to solve real world problems');
insert into related_coursework (applicationId, name, summary) values (200, 'Logic and Computation', 'Applied multiple high level algorithms to solve real world problems');
insert into related_coursework (applicationId, name, summary) values (421, 'Algorithms and Data', 'Focused on the development pipeline of applications');
insert into related_coursework (applicationId, name, summary) values (411, 'Human Computer Interactions', 'Designed complex objects to develop web applications');
insert into related_coursework (applicationId, name, summary) values (87, 'Human Computer Interactions', 'Focused on the development pipeline of applications');
insert into related_coursework (applicationId, name, summary) values (410, 'Logic and Computation', 'Focused on the development pipeline of applications');
insert into related_coursework (applicationId, name, summary) values (424, 'Fundamentals of Software Engineering', 'Designed complex objects to develop web applications');
insert into related_coursework (applicationId, name, summary) values (85, 'Advanced Database Systems', 'Applied multiple high level algorithms to solve real world problems');
insert into related_coursework (applicationId, name, summary) values (405, 'Human Computer Interactions', 'Applied multiple high level algorithms to solve real world problems');
insert into related_coursework (applicationId, name, summary) values (395, 'Object-Oriented Design', 'Designed complex objects to develop web applications');
insert into related_coursework (applicationId, name, summary) values (287, 'Fundamentals of Software Engineering', 'Focused on the development pipeline of applications');
insert into related_coursework (applicationId, name, summary) values (454, 'Logic and Computation', 'Designed complex objects to develop web applications');
insert into related_coursework (applicationId, name, summary) values (351, 'Human Computer Interactions', 'Designed complex objects to develop web applications');
insert into related_coursework (applicationId, name, summary) values (51, 'Human Computer Interactions', 'Focused on the development pipeline of applications');
insert into related_coursework (applicationId, name, summary) values (95, 'Fundamentals of Software Engineering', 'Designed complex objects to develop web applications');
insert into related_coursework (applicationId, name, summary) values (325, 'Algorithms and Data', 'Focus on database management and design');
insert into related_coursework (applicationId, name, summary) values (206, 'Object-Oriented Design', 'Applied multiple high level algorithms to solve real world problems');
insert into related_coursework (applicationId, name, summary) values (485, 'Fundamentals of Software Engineering', 'Focused on the development pipeline of applications');
insert into related_coursework (applicationId, name, summary) values (480, 'Fundamentals of Software Engineering', 'Designed complex objects to develop web applications');
insert into related_coursework (applicationId, name, summary) values (53, 'Algorithms and Data', 'Focus on database management and design');
insert into related_coursework (applicationId, name, summary) values (154, 'Object-Oriented Design', 'Focused on the development pipeline of applications');
insert into related_coursework (applicationId, name, summary) values (66, 'Logic and Computation', 'Focused on the development pipeline of applications');
insert into related_coursework (applicationId, name, summary) values (432, 'Advanced Database Systems', 'Focus on database management and design');
insert into related_coursework (applicationId, name, summary) values (107, 'Human Computer Interactions', 'Applied multiple high level algorithms to solve real world problems');
insert into related_coursework (applicationId, name, summary) values (63, 'Object-Oriented Design', 'Designed complex objects to develop web applications');
insert into related_coursework (applicationId, name, summary) values (370, 'Algorithms and Data', 'Focus on database management and design');
insert into related_coursework (applicationId, name, summary) values (149, 'Algorithms and Data', 'Applied multiple high level algorithms to solve real world problems');
insert into related_coursework (applicationId, name, summary) values (477, 'Human Computer Interactions', 'Focused on the development pipeline of applications');
insert into related_coursework (applicationId, name, summary) values (423, 'Object-Oriented Design', 'Focused on the development pipeline of applications');
insert into related_coursework (applicationId, name, summary) values (468, 'Fundamentals of Software Engineering', 'Designed complex objects to develop web applications');
insert into related_coursework (applicationId, name, summary) values (414, 'Fundamentals of Software Engineering', 'Focus on database management and design');
insert into related_coursework (applicationId, name, summary) values (477, 'Object-Oriented Design', 'Focused on the development pipeline of applications');
insert into related_coursework (applicationId, name, summary) values (125, 'Human Computer Interactions', 'Designed complex objects to develop web applications');
insert into related_coursework (applicationId, name, summary) values (432, 'Logic and Computation', 'Focus on database management and design');
insert into related_coursework (applicationId, name, summary) values (237, 'Algorithms and Data', 'Focus on database management and design');
insert into related_coursework (applicationId, name, summary) values (443, 'Algorithms and Data', 'Focus on database management and design');
insert into related_coursework (applicationId, name, summary) values (235, 'Fundamentals of Software Engineering', 'Designed complex objects to develop web applications');
insert into related_coursework (applicationId, name, summary) values (477, 'Algorithms and Data', 'Focused on the development pipeline of applications');
insert into related_coursework (applicationId, name, summary) values (75, 'Fundamentals of Software Engineering', 'Focus on database management and design');
insert into related_coursework (applicationId, name, summary) values (285, 'Algorithms and Data', 'Designed complex objects to develop web applications');
insert into related_coursework (applicationId, name, summary) values (219, 'Logic and Computation', 'Focused on the development pipeline of applications');
insert into related_coursework (applicationId, name, summary) values (445, 'Advanced Database Systems', 'Designed complex objects to develop web applications');
insert into related_coursework (applicationId, name, summary) values (251, 'Object-Oriented Design', 'Designed complex objects to develop web applications');
insert into related_coursework (applicationId, name, summary) values (448, 'Object-Oriented Design', 'Focused on the development pipeline of applications');
insert into related_coursework (applicationId, name, summary) values (171, 'Algorithms and Data', 'Applied multiple high level algorithms to solve real world problems');
insert into related_coursework (applicationId, name, summary) values (197, 'Logic and Computation', 'Designed complex objects to develop web applications');
insert into related_coursework (applicationId, name, summary) values (157, 'Logic and Computation', 'Focus on database management and design');
insert into related_coursework (applicationId, name, summary) values (31, 'Logic and Computation', 'Focused on the development pipeline of applications');
insert into related_coursework (applicationId, name, summary) values (123, 'Human Computer Interactions', 'Applied multiple high level algorithms to solve real world problems');
insert into related_coursework (applicationId, name, summary) values (487, 'Algorithms and Data', 'Focus on database management and design');
insert into related_coursework (applicationId, name, summary) values (329, 'Fundamentals of Software Engineering', 'Designed complex objects to develop web applications');
insert into related_coursework (applicationId, name, summary) values (108, 'Logic and Computation', 'Focus on database management and design');
insert into related_coursework (applicationId, name, summary) values (271, 'Logic and Computation', 'Applied multiple high level algorithms to solve real world problems');
insert into related_coursework (applicationId, name, summary) values (64, 'Algorithms and Data', 'Designed complex objects to develop web applications');
insert into related_coursework (applicationId, name, summary) values (372, 'Algorithms and Data', 'Focused on the development pipeline of applications');
insert into related_coursework (applicationId, name, summary) values (218, 'Fundamentals of Software Engineering', 'Applied multiple high level algorithms to solve real world problems');
insert into related_coursework (applicationId, name, summary) values (402, 'Algorithms and Data', 'Focused on the development pipeline of applications');
insert into related_coursework (applicationId, name, summary) values (341, 'Object-Oriented Design', 'Designed complex objects to develop web applications');
insert into related_coursework (applicationId, name, summary) values (461, 'Object-Oriented Design', 'Applied multiple high level algorithms to solve real world problems');
insert into related_coursework (applicationId, name, summary) values (398, 'Human Computer Interactions', 'Designed complex objects to develop web applications');
insert into related_coursework (applicationId, name, summary) values (433, 'Fundamentals of Software Engineering', 'Focused on the development pipeline of applications');
insert into related_coursework (applicationId, name, summary) values (281, 'Human Computer Interactions', 'Designed complex objects to develop web applications');
insert into related_coursework (applicationId, name, summary) values (406, 'Logic and Computation', 'Focused on the development pipeline of applications');
insert into related_coursework (applicationId, name, summary) values (143, 'Algorithms and Data', 'Designed complex objects to develop web applications');
insert into related_coursework (applicationId, name, summary) values (208, 'Logic and Computation', 'Designed complex objects to develop web applications');
insert into related_coursework (applicationId, name, summary) values (142, 'Human Computer Interactions', 'Focused on the development pipeline of applications');
insert into related_coursework (applicationId, name, summary) values (202, 'Human Computer Interactions', 'Applied multiple high level algorithms to solve real world problems');
insert into related_coursework (applicationId, name, summary) values (486, 'Fundamentals of Software Engineering', 'Applied multiple high level algorithms to solve real world problems');
insert into related_coursework (applicationId, name, summary) values (235, 'Object-Oriented Design', 'Focused on the development pipeline of applications');
insert into related_coursework (applicationId, name, summary) values (207, 'Logic and Computation', 'Designed complex objects to develop web applications');
insert into related_coursework (applicationId, name, summary) values (349, 'Logic and Computation', 'Focused on the development pipeline of applications');
insert into related_coursework (applicationId, name, summary) values (243, 'Logic and Computation', 'Applied multiple high level algorithms to solve real world problems');
insert into related_coursework (applicationId, name, summary) values (113, 'Fundamentals of Software Engineering', 'Designed complex objects to develop web applications');
insert into related_coursework (applicationId, name, summary) values (369, 'Logic and Computation', 'Applied multiple high level algorithms to solve real world problems');
insert into related_coursework (applicationId, name, summary) values (121, 'Algorithms and Data', 'Focus on database management and design');
insert into related_coursework (applicationId, name, summary) values (244, 'Logic and Computation', 'Designed complex objects to develop web applications');
insert into related_coursework (applicationId, name, summary) values (446, 'Object-Oriented Design', 'Focus on database management and design');
insert into related_coursework (applicationId, name, summary) values (196, 'Advanced Database Systems', 'Applied multiple high level algorithms to solve real world problems');
insert into related_coursework (applicationId, name, summary) values (75, 'Fundamentals of Software Engineering', 'Focus on database management and design');
insert into related_coursework (applicationId, name, summary) values (330, 'Logic and Computation', 'Designed complex objects to develop web applications');
insert into related_coursework (applicationId, name, summary) values (91, 'Algorithms and Data', 'Focused on the development pipeline of applications');
insert into related_coursework (applicationId, name, summary) values (235, 'Advanced Database Systems', 'Applied multiple high level algorithms to solve real world problems');
insert into related_coursework (applicationId, name, summary) values (42, 'Human Computer Interactions', 'Focus on database management and design');
insert into related_coursework (applicationId, name, summary) values (42, 'Human Computer Interactions', 'Focus on database management and design');
insert into related_coursework (applicationId, name, summary) values (260, 'Logic and Computation', 'Focused on the development pipeline of applications');
insert into related_coursework (applicationId, name, summary) values (50, 'Logic and Computation', 'Designed complex objects to develop web applications');
insert into related_coursework (applicationId, name, summary) values (325, 'Advanced Database Systems', 'Applied multiple high level algorithms to solve real world problems');
insert into related_coursework (applicationId, name, summary) values (343, 'Logic and Computation', 'Applied multiple high level algorithms to solve real world problems');
insert into related_coursework (applicationId, name, summary) values (174, 'Object-Oriented Design', 'Applied multiple high level algorithms to solve real world problems');
insert into related_coursework (applicationId, name, summary) values (215, 'Logic and Computation', 'Designed complex objects to develop web applications');
insert into related_coursework (applicationId, name, summary) values (110, 'Object-Oriented Design', 'Focused on the development pipeline of applications');
insert into related_coursework (applicationId, name, summary) values (165, 'Object-Oriented Design', 'Focus on database management and design');
insert into related_coursework (applicationId, name, summary) values (491, 'Algorithms and Data', 'Designed complex objects to develop web applications');
insert into related_coursework (applicationId, name, summary) values (291, 'Algorithms and Data', 'Designed complex objects to develop web applications');
insert into related_coursework (applicationId, name, summary) values (180, 'Object-Oriented Design', 'Applied multiple high level algorithms to solve real world problems');
insert into related_coursework (applicationId, name, summary) values (41, 'Advanced Database Systems', 'Focus on database management and design');
insert into related_coursework (applicationId, name, summary) values (70, 'Fundamentals of Software Engineering', 'Designed complex objects to develop web applications');
insert into related_coursework (applicationId, name, summary) values (456, 'Fundamentals of Software Engineering', 'Applied multiple high level algorithms to solve real world problems');
insert into related_coursework (applicationId, name, summary) values (24, 'Human Computer Interactions', 'Applied multiple high level algorithms to solve real world problems');
insert into related_coursework (applicationId, name, summary) values (388, 'Algorithms and Data', 'Focus on database management and design');
insert into related_coursework (applicationId, name, summary) values (450, 'Advanced Database Systems', 'Designed complex objects to develop web applications');
insert into related_coursework (applicationId, name, summary) values (230, 'Algorithms and Data', 'Designed complex objects to develop web applications');
insert into related_coursework (applicationId, name, summary) values (115, 'Human Computer Interactions', 'Focus on database management and design');
insert into related_coursework (applicationId, name, summary) values (5, 'Human Computer Interactions', 'Designed complex objects to develop web applications');
insert into related_coursework (applicationId, name, summary) values (244, 'Logic and Computation', 'Focused on the development pipeline of applications');
insert into related_coursework (applicationId, name, summary) values (196, 'Human Computer Interactions', 'Designed complex objects to develop web applications');
insert into related_coursework (applicationId, name, summary) values (146, 'Fundamentals of Software Engineering', 'Designed complex objects to develop web applications');
insert into related_coursework (applicationId, name, summary) values (136, 'Object-Oriented Design', 'Applied multiple high level algorithms to solve real world problems');
insert into related_coursework (applicationId, name, summary) values (77, 'Algorithms and Data', 'Applied multiple high level algorithms to solve real world problems');
insert into related_coursework (applicationId, name, summary) values (349, 'Human Computer Interactions', 'Focused on the development pipeline of applications');
insert into related_coursework (applicationId, name, summary) values (456, 'Fundamentals of Software Engineering', 'Designed complex objects to develop web applications');
insert into related_coursework (applicationId, name, summary) values (241, 'Human Computer Interactions', 'Applied multiple high level algorithms to solve real world problems');
insert into related_coursework (applicationId, name, summary) values (249, 'Advanced Database Systems', 'Applied multiple high level algorithms to solve real world problems');
insert into related_coursework (applicationId, name, summary) values (6, 'Human Computer Interactions', 'Designed complex objects to develop web applications');
insert into related_coursework (applicationId, name, summary) values (116, 'Algorithms and Data', 'Designed complex objects to develop web applications');
insert into related_coursework (applicationId, name, summary) values (445, 'Fundamentals of Software Engineering', 'Focused on the development pipeline of applications');
insert into related_coursework (applicationId, name, summary) values (250, 'Object-Oriented Design', 'Designed complex objects to develop web applications');
insert into related_coursework (applicationId, name, summary) values (407, 'Human Computer Interactions', 'Applied multiple high level algorithms to solve real world problems');
insert into related_coursework (applicationId, name, summary) values (392, 'Logic and Computation', 'Applied multiple high level algorithms to solve real world problems');
insert into related_coursework (applicationId, name, summary) values (171, 'Human Computer Interactions', 'Focus on database management and design');
insert into related_coursework (applicationId, name, summary) values (35, 'Logic and Computation', 'Applied multiple high level algorithms to solve real world problems');
insert into related_coursework (applicationId, name, summary) values (431, 'Human Computer Interactions', 'Applied multiple high level algorithms to solve real world problems');
insert into related_coursework (applicationId, name, summary) values (369, 'Algorithms and Data', 'Applied multiple high level algorithms to solve real world problems');
insert into related_coursework (applicationId, name, summary) values (368, 'Fundamentals of Software Engineering', 'Focus on database management and design');
insert into related_coursework (applicationId, name, summary) values (260, 'Human Computer Interactions', 'Focus on database management and design');
insert into related_coursework (applicationId, name, summary) values (315, 'Object-Oriented Design', 'Applied multiple high level algorithms to solve real world problems');
insert into related_coursework (applicationId, name, summary) values (100, 'Logic and Computation', 'Designed complex objects to develop web applications');
insert into related_coursework (applicationId, name, summary) values (221, 'Logic and Computation', 'Focus on database management and design');
insert into related_coursework (applicationId, name, summary) values (393, 'Human Computer Interactions', 'Focus on database management and design');
insert into related_coursework (applicationId, name, summary) values (469, 'Fundamentals of Software Engineering', 'Focused on the development pipeline of applications');
insert into related_coursework (applicationId, name, summary) values (425, 'Object-Oriented Design', 'Applied multiple high level algorithms to solve real world problems');
insert into related_coursework (applicationId, name, summary) values (161, 'Object-Oriented Design', 'Designed complex objects to develop web applications');
insert into related_coursework (applicationId, name, summary) values (423, 'Object-Oriented Design', 'Focus on database management and design');
insert into related_coursework (applicationId, name, summary) values (50, 'Logic and Computation', 'Designed complex objects to develop web applications');
insert into related_coursework (applicationId, name, summary) values (200, 'Human Computer Interactions', 'Applied multiple high level algorithms to solve real world problems');
insert into related_coursework (applicationId, name, summary) values (103, 'Logic and Computation', 'Focus on database management and design');
insert into related_coursework (applicationId, name, summary) values (158, 'Human Computer Interactions', 'Designed complex objects to develop web applications');
insert into related_coursework (applicationId, name, summary) values (479, 'Advanced Database Systems', 'Focus on database management and design');
insert into related_coursework (applicationId, name, summary) values (387, 'Human Computer Interactions', 'Applied multiple high level algorithms to solve real world problems');
insert into related_coursework (applicationId, name, summary) values (451, 'Object-Oriented Design', 'Applied multiple high level algorithms to solve real world problems');
insert into related_coursework (applicationId, name, summary) values (168, 'Advanced Database Systems', 'Focus on database management and design');
insert into related_coursework (applicationId, name, summary) values (253, 'Algorithms and Data', 'Designed complex objects to develop web applications');
insert into related_coursework (applicationId, name, summary) values (3, 'Advanced Database Systems', 'Focused on the development pipeline of applications');
insert into related_coursework (applicationId, name, summary) values (494, 'Fundamentals of Software Engineering', 'Designed complex objects to develop web applications');
insert into related_coursework (applicationId, name, summary) values (123, 'Human Computer Interactions', 'Designed complex objects to develop web applications');
insert into related_coursework (applicationId, name, summary) values (111, 'Algorithms and Data', 'Focused on the development pipeline of applications');
insert into related_coursework (applicationId, name, summary) values (139, 'Human Computer Interactions', 'Focus on database management and design');
insert into related_coursework (applicationId, name, summary) values (269, 'Human Computer Interactions', 'Applied multiple high level algorithms to solve real world problems');
insert into related_coursework (applicationId, name, summary) values (356, 'Object-Oriented Design', 'Focused on the development pipeline of applications');
insert into related_coursework (applicationId, name, summary) values (130, 'Advanced Database Systems', 'Focus on database management and design');
insert into related_coursework (applicationId, name, summary) values (335, 'Object-Oriented Design', 'Applied multiple high level algorithms to solve real world problems');
insert into related_coursework (applicationId, name, summary) values (40, 'Advanced Database Systems', 'Focus on database management and design');
insert into related_coursework (applicationId, name, summary) values (450, 'Fundamentals of Software Engineering', 'Applied multiple high level algorithms to solve real world problems');
insert into related_coursework (applicationId, name, summary) values (59, 'Advanced Database Systems', 'Applied multiple high level algorithms to solve real world problems');
insert into related_coursework (applicationId, name, summary) values (24, 'Advanced Database Systems', 'Focused on the development pipeline of applications');
insert into related_coursework (applicationId, name, summary) values (280, 'Algorithms and Data', 'Focus on database management and design');
insert into related_coursework (applicationId, name, summary) values (468, 'Object-Oriented Design', 'Applied multiple high level algorithms to solve real world problems');
insert into related_coursework (applicationId, name, summary) values (9, 'Fundamentals of Software Engineering', 'Applied multiple high level algorithms to solve real world problems');
insert into related_coursework (applicationId, name, summary) values (478, 'Algorithms and Data', 'Designed complex objects to develop web applications');
insert into related_coursework (applicationId, name, summary) values (493, 'Logic and Computation', 'Focus on database management and design');
