USE cosint;

-- mock data work experience
insert into work_experience (applicationId, name, summary) values (382, 'Geologist III', 'Created a web application that tracks the user''s daily caloric intake');
insert into work_experience (applicationId, name, summary) values (21, 'Librarian', 'Developed a new algorithm to predict bitcoin prices');
insert into work_experience (applicationId, name, summary) values (387, 'Account Coordinator', 'Managed a team of 20 software interns');
insert into work_experience (applicationId, name, summary) values (400, 'Accountant IV', 'Created a web application that tracks the user''s daily caloric intake');
insert into work_experience (applicationId, name, summary) values (175, 'Senior Sales Associate', 'Developed a new algorithm to predict bitcoin prices');
insert into work_experience (applicationId, name, summary) values (394, 'Assistant Professor', 'Created a web application that tracks the user''s daily caloric intake');
insert into work_experience (applicationId, name, summary) values (186, 'Financial Advisor', 'Developed a new algorithm to predict bitcoin prices');
insert into work_experience (applicationId, name, summary) values (26, 'Health Coach I', 'Designed a new UI for Google');
insert into work_experience (applicationId, name, summary) values (144, 'Recruiting Manager', 'Developed a new algorithm to predict bitcoin prices');
insert into work_experience (applicationId, name, summary) values (187, 'VP Marketing', 'Created a web application that tracks the user''s daily caloric intake');
insert into work_experience (applicationId, name, summary) values (471, 'Food Chemist', 'Developed a new algorithm to predict bitcoin prices');
insert into work_experience (applicationId, name, summary) values (124, 'Account Executive', 'Managed a team of 20 software interns');
insert into work_experience (applicationId, name, summary) values (363, 'VP Accounting', 'Developed a new algorithm to predict bitcoin prices');
insert into work_experience (applicationId, name, summary) values (418, 'General Manager', 'Managed a team of 20 software interns');
insert into work_experience (applicationId, name, summary) values (3, 'Accountant I', 'Created a web application that tracks the user''s daily caloric intake');
insert into work_experience (applicationId, name, summary) values (276, 'Nuclear Power Engineer', 'Developed a new algorithm to predict bitcoin prices');
insert into work_experience (applicationId, name, summary) values (238, 'Occupational Therapist', 'Created a web application that tracks the user''s daily caloric intake');
insert into work_experience (applicationId, name, summary) values (351, 'Chief Design Engineer', 'Developed a new algorithm to predict bitcoin prices');
insert into work_experience (applicationId, name, summary) values (245, 'Research Associate', 'Created a web application that tracks the user''s daily caloric intake');
insert into work_experience (applicationId, name, summary) values (22, 'Automation Specialist III', 'Created a web application that tracks the user''s daily caloric intake');
insert into work_experience (applicationId, name, summary) values (357, 'Teacher', 'Developed a new algorithm to predict bitcoin prices');
insert into work_experience (applicationId, name, summary) values (485, 'Account Coordinator', 'Developed a new algorithm to predict bitcoin prices');
insert into work_experience (applicationId, name, summary) values (272, 'Desktop Support Technician', 'Managed a team of 20 software interns');
insert into work_experience (applicationId, name, summary) values (442, 'Computer Systems Analyst IV', 'Designed a new UI for Google');
insert into work_experience (applicationId, name, summary) values (82, 'Structural Analysis Engineer', 'Managed a team of 20 software interns');
insert into work_experience (applicationId, name, summary) values (358, 'Physical Therapy Assistant', 'Developed a new algorithm to predict bitcoin prices');
insert into work_experience (applicationId, name, summary) values (381, 'Graphic Designer', 'Designed a new UI for Google');
insert into work_experience (applicationId, name, summary) values (108, 'Librarian', 'Created a web application that tracks the user''s daily caloric intake');
insert into work_experience (applicationId, name, summary) values (492, 'Information Systems Manager', 'Designed a new UI for Google');
insert into work_experience (applicationId, name, summary) values (139, 'Environmental Specialist', 'Developed a new algorithm to predict bitcoin prices');
insert into work_experience (applicationId, name, summary) values (175, 'Desktop Support Technician', 'Managed a team of 20 software interns');
insert into work_experience (applicationId, name, summary) values (348, 'Account Representative IV', 'Managed a team of 20 software interns');
insert into work_experience (applicationId, name, summary) values (424, 'Quality Control Specialist', 'Created a web application that tracks the user''s daily caloric intake');
insert into work_experience (applicationId, name, summary) values (365, 'Assistant Professor', 'Developed a new algorithm to predict bitcoin prices');
insert into work_experience (applicationId, name, summary) values (470, 'Pharmacist', 'Designed a new UI for Google');
insert into work_experience (applicationId, name, summary) values (440, 'Speech Pathologist', 'Created a web application that tracks the user''s daily caloric intake');
insert into work_experience (applicationId, name, summary) values (327, 'Web Developer IV', 'Developed a new algorithm to predict bitcoin prices');
insert into work_experience (applicationId, name, summary) values (390, 'VP Accounting', 'Managed a team of 20 software interns');
insert into work_experience (applicationId, name, summary) values (322, 'Systems Administrator III', 'Managed a team of 20 software interns');
insert into work_experience (applicationId, name, summary) values (219, 'Mechanical Systems Engineer', 'Developed a new algorithm to predict bitcoin prices');
insert into work_experience (applicationId, name, summary) values (379, 'Senior Quality Engineer', 'Managed a team of 20 software interns');
insert into work_experience (applicationId, name, summary) values (229, 'Design Engineer', 'Created a web application that tracks the user''s daily caloric intake');
insert into work_experience (applicationId, name, summary) values (27, 'Database Administrator III', 'Created a web application that tracks the user''s daily caloric intake');
insert into work_experience (applicationId, name, summary) values (239, 'Marketing Assistant', 'Designed a new UI for Google');
insert into work_experience (applicationId, name, summary) values (436, 'VP Quality Control', 'Managed a team of 20 software interns');
insert into work_experience (applicationId, name, summary) values (226, 'Senior Financial Analyst', 'Developed a new algorithm to predict bitcoin prices');
insert into work_experience (applicationId, name, summary) values (107, 'Assistant Professor', 'Created a web application that tracks the user''s daily caloric intake');
insert into work_experience (applicationId, name, summary) values (214, 'Operator', 'Managed a team of 20 software interns');
insert into work_experience (applicationId, name, summary) values (152, 'Senior Sales Associate', 'Developed a new algorithm to predict bitcoin prices');
insert into work_experience (applicationId, name, summary) values (410, 'Accounting Assistant II', 'Managed a team of 20 software interns');
insert into work_experience (applicationId, name, summary) values (262, 'Accountant II', 'Created a web application that tracks the user''s daily caloric intake');
insert into work_experience (applicationId, name, summary) values (219, 'Assistant Manager', 'Developed a new algorithm to predict bitcoin prices');
insert into work_experience (applicationId, name, summary) values (75, 'Speech Pathologist', 'Designed a new UI for Google');
insert into work_experience (applicationId, name, summary) values (292, 'Business Systems Development Analyst', 'Managed a team of 20 software interns');
insert into work_experience (applicationId, name, summary) values (397, 'Accountant I', 'Developed a new algorithm to predict bitcoin prices');
insert into work_experience (applicationId, name, summary) values (415, 'Administrative Officer', 'Developed a new algorithm to predict bitcoin prices');
insert into work_experience (applicationId, name, summary) values (61, 'Payment Adjustment Coordinator', 'Created a web application that tracks the user''s daily caloric intake');
insert into work_experience (applicationId, name, summary) values (45, 'Developer III', 'Designed a new UI for Google');
insert into work_experience (applicationId, name, summary) values (477, 'VP Accounting', 'Managed a team of 20 software interns');
insert into work_experience (applicationId, name, summary) values (414, 'Environmental Specialist', 'Designed a new UI for Google');
insert into work_experience (applicationId, name, summary) values (83, 'Project Manager', 'Managed a team of 20 software interns');
insert into work_experience (applicationId, name, summary) values (226, 'Engineer IV', 'Developed a new algorithm to predict bitcoin prices');
insert into work_experience (applicationId, name, summary) values (350, 'Nuclear Power Engineer', 'Created a web application that tracks the user''s daily caloric intake');
insert into work_experience (applicationId, name, summary) values (380, 'Cost Accountant', 'Created a web application that tracks the user''s daily caloric intake');
insert into work_experience (applicationId, name, summary) values (185, 'Sales Representative', 'Created a web application that tracks the user''s daily caloric intake');
insert into work_experience (applicationId, name, summary) values (434, 'Geologist II', 'Developed a new algorithm to predict bitcoin prices');
insert into work_experience (applicationId, name, summary) values (308, 'Quality Engineer', 'Designed a new UI for Google');
insert into work_experience (applicationId, name, summary) values (314, 'Software Test Engineer II', 'Created a web application that tracks the user''s daily caloric intake');
insert into work_experience (applicationId, name, summary) values (315, 'Assistant Professor', 'Developed a new algorithm to predict bitcoin prices');
insert into work_experience (applicationId, name, summary) values (89, 'Structural Engineer', 'Created a web application that tracks the user''s daily caloric intake');
insert into work_experience (applicationId, name, summary) values (483, 'Quality Engineer', 'Created a web application that tracks the user''s daily caloric intake');
insert into work_experience (applicationId, name, summary) values (364, 'Social Worker', 'Developed a new algorithm to predict bitcoin prices');
insert into work_experience (applicationId, name, summary) values (170, 'Nurse Practicioner', 'Created a web application that tracks the user''s daily caloric intake');
insert into work_experience (applicationId, name, summary) values (347, 'Project Manager', 'Developed a new algorithm to predict bitcoin prices');
insert into work_experience (applicationId, name, summary) values (307, 'Environmental Tech', 'Developed a new algorithm to predict bitcoin prices');
insert into work_experience (applicationId, name, summary) values (197, 'Senior Quality Engineer', 'Developed a new algorithm to predict bitcoin prices');
insert into work_experience (applicationId, name, summary) values (219, 'Social Worker', 'Managed a team of 20 software interns');
insert into work_experience (applicationId, name, summary) values (203, 'Internal Auditor', 'Developed a new algorithm to predict bitcoin prices');
insert into work_experience (applicationId, name, summary) values (35, 'Media Manager I', 'Developed a new algorithm to predict bitcoin prices');
insert into work_experience (applicationId, name, summary) values (493, 'Research Associate', 'Created a web application that tracks the user''s daily caloric intake');
insert into work_experience (applicationId, name, summary) values (450, 'Electrical Engineer', 'Managed a team of 20 software interns');
insert into work_experience (applicationId, name, summary) values (190, 'Staff Accountant I', 'Designed a new UI for Google');
insert into work_experience (applicationId, name, summary) values (183, 'Sales Representative', 'Developed a new algorithm to predict bitcoin prices');
insert into work_experience (applicationId, name, summary) values (205, 'Account Coordinator', 'Designed a new UI for Google');
insert into work_experience (applicationId, name, summary) values (444, 'Human Resources Manager', 'Developed a new algorithm to predict bitcoin prices');
insert into work_experience (applicationId, name, summary) values (412, 'Graphic Designer', 'Managed a team of 20 software interns');
insert into work_experience (applicationId, name, summary) values (449, 'Senior Quality Engineer', 'Created a web application that tracks the user''s daily caloric intake');
insert into work_experience (applicationId, name, summary) values (148, 'Office Assistant II', 'Designed a new UI for Google');
insert into work_experience (applicationId, name, summary) values (14, 'Social Worker', 'Created a web application that tracks the user''s daily caloric intake');
insert into work_experience (applicationId, name, summary) values (355, 'Account Executive', 'Created a web application that tracks the user''s daily caloric intake');
insert into work_experience (applicationId, name, summary) values (366, 'Registered Nurse', 'Designed a new UI for Google');
insert into work_experience (applicationId, name, summary) values (285, 'Senior Developer', 'Created a web application that tracks the user''s daily caloric intake');
insert into work_experience (applicationId, name, summary) values (127, 'Senior Sales Associate', 'Designed a new UI for Google');
insert into work_experience (applicationId, name, summary) values (485, 'Pharmacist', 'Designed a new UI for Google');
insert into work_experience (applicationId, name, summary) values (330, 'Accounting Assistant III', 'Designed a new UI for Google');
insert into work_experience (applicationId, name, summary) values (197, 'Systems Administrator II', 'Designed a new UI for Google');
insert into work_experience (applicationId, name, summary) values (426, 'Accountant II', 'Developed a new algorithm to predict bitcoin prices');
insert into work_experience (applicationId, name, summary) values (428, 'Human Resources Assistant III', 'Managed a team of 20 software interns');
insert into work_experience (applicationId, name, summary) values (447, 'Senior Developer', 'Managed a team of 20 software interns');
insert into work_experience (applicationId, name, summary) values (245, 'Information Systems Manager', 'Created a web application that tracks the user''s daily caloric intake');
insert into work_experience (applicationId, name, summary) values (182, 'Business Systems Development Analyst', 'Developed a new algorithm to predict bitcoin prices');
insert into work_experience (applicationId, name, summary) values (451, 'Senior Sales Associate', 'Created a web application that tracks the user''s daily caloric intake');
insert into work_experience (applicationId, name, summary) values (71, 'Operator', 'Created a web application that tracks the user''s daily caloric intake');
insert into work_experience (applicationId, name, summary) values (116, 'Assistant Manager', 'Created a web application that tracks the user''s daily caloric intake');
insert into work_experience (applicationId, name, summary) values (414, 'Professor', 'Developed a new algorithm to predict bitcoin prices');
insert into work_experience (applicationId, name, summary) values (137, 'Biostatistician I', 'Managed a team of 20 software interns');
insert into work_experience (applicationId, name, summary) values (386, 'Staff Accountant II', 'Managed a team of 20 software interns');
insert into work_experience (applicationId, name, summary) values (132, 'Account Executive', 'Developed a new algorithm to predict bitcoin prices');
insert into work_experience (applicationId, name, summary) values (32, 'Automation Specialist I', 'Managed a team of 20 software interns');
insert into work_experience (applicationId, name, summary) values (196, 'Desktop Support Technician', 'Managed a team of 20 software interns');
insert into work_experience (applicationId, name, summary) values (187, 'Legal Assistant', 'Developed a new algorithm to predict bitcoin prices');
insert into work_experience (applicationId, name, summary) values (12, 'Budget/Accounting Analyst I', 'Developed a new algorithm to predict bitcoin prices');
insert into work_experience (applicationId, name, summary) values (407, 'Food Chemist', 'Created a web application that tracks the user''s daily caloric intake');
insert into work_experience (applicationId, name, summary) values (166, 'Graphic Designer', 'Developed a new algorithm to predict bitcoin prices');
insert into work_experience (applicationId, name, summary) values (13, 'Data Coordinator', 'Managed a team of 20 software interns');
insert into work_experience (applicationId, name, summary) values (106, 'Senior Quality Engineer', 'Created a web application that tracks the user''s daily caloric intake');
insert into work_experience (applicationId, name, summary) values (178, 'Tax Accountant', 'Designed a new UI for Google');
insert into work_experience (applicationId, name, summary) values (12, 'Chief Design Engineer', 'Created a web application that tracks the user''s daily caloric intake');
insert into work_experience (applicationId, name, summary) values (214, 'Assistant Professor', 'Developed a new algorithm to predict bitcoin prices');
insert into work_experience (applicationId, name, summary) values (4, 'Legal Assistant', 'Designed a new UI for Google');
insert into work_experience (applicationId, name, summary) values (160, 'Professor', 'Developed a new algorithm to predict bitcoin prices');
insert into work_experience (applicationId, name, summary) values (210, 'Programmer IV', 'Developed a new algorithm to predict bitcoin prices');
insert into work_experience (applicationId, name, summary) values (493, 'Payment Adjustment Coordinator', 'Designed a new UI for Google');
insert into work_experience (applicationId, name, summary) values (348, 'Graphic Designer', 'Designed a new UI for Google');
insert into work_experience (applicationId, name, summary) values (340, 'Software Test Engineer IV', 'Managed a team of 20 software interns');
insert into work_experience (applicationId, name, summary) values (255, 'Media Manager III', 'Designed a new UI for Google');
insert into work_experience (applicationId, name, summary) values (442, 'Information Systems Manager', 'Developed a new algorithm to predict bitcoin prices');
insert into work_experience (applicationId, name, summary) values (133, 'Editor', 'Managed a team of 20 software interns');
insert into work_experience (applicationId, name, summary) values (210, 'Human Resources Manager', 'Designed a new UI for Google');
insert into work_experience (applicationId, name, summary) values (441, 'Administrative Officer', 'Designed a new UI for Google');
insert into work_experience (applicationId, name, summary) values (281, 'Recruiter', 'Developed a new algorithm to predict bitcoin prices');
insert into work_experience (applicationId, name, summary) values (270, 'Teacher', 'Developed a new algorithm to predict bitcoin prices');
insert into work_experience (applicationId, name, summary) values (167, 'Account Coordinator', 'Designed a new UI for Google');
insert into work_experience (applicationId, name, summary) values (177, 'Analog Circuit Design manager', 'Developed a new algorithm to predict bitcoin prices');
insert into work_experience (applicationId, name, summary) values (216, 'Data Coordinator', 'Managed a team of 20 software interns');
insert into work_experience (applicationId, name, summary) values (483, 'Quality Engineer', 'Managed a team of 20 software interns');
insert into work_experience (applicationId, name, summary) values (228, 'Internal Auditor', 'Developed a new algorithm to predict bitcoin prices');
insert into work_experience (applicationId, name, summary) values (19, 'VP Marketing', 'Designed a new UI for Google');
insert into work_experience (applicationId, name, summary) values (104, 'Legal Assistant', 'Designed a new UI for Google');
insert into work_experience (applicationId, name, summary) values (76, 'Graphic Designer', 'Developed a new algorithm to predict bitcoin prices');
insert into work_experience (applicationId, name, summary) values (189, 'Engineer I', 'Created a web application that tracks the user''s daily caloric intake');
insert into work_experience (applicationId, name, summary) values (377, 'Food Chemist', 'Created a web application that tracks the user''s daily caloric intake');
insert into work_experience (applicationId, name, summary) values (40, 'Accountant II', 'Developed a new algorithm to predict bitcoin prices');
insert into work_experience (applicationId, name, summary) values (416, 'Senior Developer', 'Designed a new UI for Google');
insert into work_experience (applicationId, name, summary) values (113, 'Senior Quality Engineer', 'Developed a new algorithm to predict bitcoin prices');
insert into work_experience (applicationId, name, summary) values (247, 'Web Designer IV', 'Developed a new algorithm to predict bitcoin prices');
insert into work_experience (applicationId, name, summary) values (358, 'Quality Engineer', 'Designed a new UI for Google');
insert into work_experience (applicationId, name, summary) values (75, 'Data Coordinator', 'Designed a new UI for Google');
insert into work_experience (applicationId, name, summary) values (253, 'Geologist I', 'Developed a new algorithm to predict bitcoin prices');
insert into work_experience (applicationId, name, summary) values (66, 'Data Coordinator', 'Designed a new UI for Google');
insert into work_experience (applicationId, name, summary) values (375, 'Executive Secretary', 'Designed a new UI for Google');
insert into work_experience (applicationId, name, summary) values (119, 'Technical Writer', 'Designed a new UI for Google');
insert into work_experience (applicationId, name, summary) values (233, 'Legal Assistant', 'Created a web application that tracks the user''s daily caloric intake');
insert into work_experience (applicationId, name, summary) values (320, 'Electrical Engineer', 'Developed a new algorithm to predict bitcoin prices');
insert into work_experience (applicationId, name, summary) values (223, 'Civil Engineer', 'Developed a new algorithm to predict bitcoin prices');
insert into work_experience (applicationId, name, summary) values (147, 'Chief Design Engineer', 'Designed a new UI for Google');
insert into work_experience (applicationId, name, summary) values (461, 'Web Developer IV', 'Developed a new algorithm to predict bitcoin prices');
insert into work_experience (applicationId, name, summary) values (114, 'Administrative Officer', 'Developed a new algorithm to predict bitcoin prices');
insert into work_experience (applicationId, name, summary) values (126, 'Information Systems Manager', 'Developed a new algorithm to predict bitcoin prices');
insert into work_experience (applicationId, name, summary) values (370, 'Civil Engineer', 'Managed a team of 20 software interns');
insert into work_experience (applicationId, name, summary) values (231, 'Operator', 'Created a web application that tracks the user''s daily caloric intake');
insert into work_experience (applicationId, name, summary) values (432, 'Computer Systems Analyst IV', 'Developed a new algorithm to predict bitcoin prices');
insert into work_experience (applicationId, name, summary) values (436, 'VP Marketing', 'Designed a new UI for Google');
insert into work_experience (applicationId, name, summary) values (90, 'Automation Specialist II', 'Designed a new UI for Google');
insert into work_experience (applicationId, name, summary) values (327, 'Structural Engineer', 'Developed a new algorithm to predict bitcoin prices');
insert into work_experience (applicationId, name, summary) values (127, 'Environmental Tech', 'Managed a team of 20 software interns');
insert into work_experience (applicationId, name, summary) values (183, 'Human Resources Assistant I', 'Created a web application that tracks the user''s daily caloric intake');
insert into work_experience (applicationId, name, summary) values (483, 'Compensation Analyst', 'Designed a new UI for Google');
insert into work_experience (applicationId, name, summary) values (437, 'Senior Developer', 'Developed a new algorithm to predict bitcoin prices');
insert into work_experience (applicationId, name, summary) values (335, 'Social Worker', 'Designed a new UI for Google');
insert into work_experience (applicationId, name, summary) values (168, 'Administrative Officer', 'Created a web application that tracks the user''s daily caloric intake');
insert into work_experience (applicationId, name, summary) values (365, 'Product Engineer', 'Developed a new algorithm to predict bitcoin prices');
insert into work_experience (applicationId, name, summary) values (414, 'Structural Analysis Engineer', 'Developed a new algorithm to predict bitcoin prices');
insert into work_experience (applicationId, name, summary) values (81, 'Assistant Media Planner', 'Managed a team of 20 software interns');
insert into work_experience (applicationId, name, summary) values (169, 'Project Manager', 'Designed a new UI for Google');
insert into work_experience (applicationId, name, summary) values (319, 'Nuclear Power Engineer', 'Designed a new UI for Google');
insert into work_experience (applicationId, name, summary) values (336, 'Recruiting Manager', 'Created a web application that tracks the user''s daily caloric intake');
insert into work_experience (applicationId, name, summary) values (474, 'Nurse', 'Managed a team of 20 software interns');
insert into work_experience (applicationId, name, summary) values (232, 'Health Coach IV', 'Developed a new algorithm to predict bitcoin prices');
insert into work_experience (applicationId, name, summary) values (53, 'Accounting Assistant I', 'Designed a new UI for Google');
insert into work_experience (applicationId, name, summary) values (394, 'Web Designer IV', 'Managed a team of 20 software interns');
insert into work_experience (applicationId, name, summary) values (457, 'Graphic Designer', 'Designed a new UI for Google');
insert into work_experience (applicationId, name, summary) values (223, 'Compensation Analyst', 'Managed a team of 20 software interns');
insert into work_experience (applicationId, name, summary) values (214, 'Assistant Professor', 'Created a web application that tracks the user''s daily caloric intake');
insert into work_experience (applicationId, name, summary) values (108, 'Actuary', 'Created a web application that tracks the user''s daily caloric intake');
insert into work_experience (applicationId, name, summary) values (341, 'Geological Engineer', 'Designed a new UI for Google');
insert into work_experience (applicationId, name, summary) values (256, 'Statistician IV', 'Managed a team of 20 software interns');
insert into work_experience (applicationId, name, summary) values (1, 'Geological Engineer', 'Managed a team of 20 software interns');
insert into work_experience (applicationId, name, summary) values (179, 'Administrative Assistant III', 'Developed a new algorithm to predict bitcoin prices');
insert into work_experience (applicationId, name, summary) values (94, 'Analog Circuit Design manager', 'Created a web application that tracks the user''s daily caloric intake');
insert into work_experience (applicationId, name, summary) values (311, 'Social Worker', 'Developed a new algorithm to predict bitcoin prices');
insert into work_experience (applicationId, name, summary) values (443, 'Analog Circuit Design manager', 'Developed a new algorithm to predict bitcoin prices');
insert into work_experience (applicationId, name, summary) values (434, 'Human Resources Manager', 'Created a web application that tracks the user''s daily caloric intake');
insert into work_experience (applicationId, name, summary) values (21, 'Clinical Specialist', 'Designed a new UI for Google');
insert into work_experience (applicationId, name, summary) values (448, 'Human Resources Manager', 'Created a web application that tracks the user''s daily caloric intake');
insert into work_experience (applicationId, name, summary) values (191, 'Analog Circuit Design manager', 'Developed a new algorithm to predict bitcoin prices');
insert into work_experience (applicationId, name, summary) values (187, 'Software Consultant', 'Designed a new UI for Google');
insert into work_experience (applicationId, name, summary) values (285, 'Legal Assistant', 'Designed a new UI for Google');
insert into work_experience (applicationId, name, summary) values (267, 'Automation Specialist II', 'Developed a new algorithm to predict bitcoin prices');
insert into work_experience (applicationId, name, summary) values (408, 'Occupational Therapist', 'Created a web application that tracks the user''s daily caloric intake');
